# Importing Packages -:

In [1]:
import pandas as pd 
import numpy as np

In [2]:
movies= pd.read_csv(r"C:\Users\DELL\Desktop\Project\Movies recommendation\tmdb_5000_movies.csv")
credits = pd.read_csv(r"C:\Users\DELL\Desktop\Project\Movies recommendation\tmdb_5000_credits.csv")

# Importing & Analysing Data -:

In [3]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

# Data Processing  -:

* I have two datasets and I am going to merge them I can merge them on basis of movie id and on movie name. Here I am going to merge on basis movies name.

In [5]:
movies = movies.merge(credits,on='title')

In [6]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

* Now i am removing the columns that are not needed for analysis

In [7]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [8]:
movies=movies[['movie_id','title','overview','genres','keywords','cast', 'crew','vote_count', 'vote_average']]

In [9]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew,vote_count,vote_average
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",11800,7.2

In [10]:
movies['title'].unique().tolist()

['Avatar',
 "Pirates of the Caribbean: At World's End",
 'Spectre',
 'The Dark Knight Rises',
 'John Carter',
 'Spider-Man 3',
 'Tangled',
 'Avengers: Age of Ultron',
 'Harry Potter and the Half-Blood Prince',
 'Batman v Superman: Dawn of Justice',
 'Superman Returns',
 'Quantum of Solace',
 "Pirates of the Caribbean: Dead Man's Chest",
 'The Lone Ranger',
 'Man of Steel',
 'The Chronicles of Narnia: Prince Caspian',
 'The Avengers',
 'Pirates of the Caribbean: On Stranger Tides',
 'Men in Black 3',
 'The Hobbit: The Battle of the Five Armies',
 'The Amazing Spider-Man',
 'Robin Hood',
 'The Hobbit: The Desolation of Smaug',
 'The Golden Compass',
 'King Kong',
 'Titanic',
 'Captain America: Civil War',
 'Battleship',
 'Jurassic World',
 'Skyfall',
 'Spider-Man 2',
 'Iron Man 3',
 'Alice in Wonderland',
 'X-Men: The Last Stand',
 'Monsters University',
 'Transformers: Revenge of the Fallen',
 'Transformers: Age of Extinction',
 'Oz: The Great and Powerful',
 'The Amazing Spider-Man 2',
 'TRON: Legacy',
 'Cars 2',
 'Green Lantern',
 'Toy Story 3',
 'Terminator Salvation',
 'Furious 7',
 'World War Z',
 'X-Men: Days of Future Past',
 'Star Trek Into Darkness',
 'Jack the Giant Slayer',
 'The Great Gatsby',
 'Prince of Persia: The Sands of Time',
 'Pacific Rim',
 'Transformers: Dark of the Moon',
 'Indiana Jones and the Kingdom of the Crystal Skull',
 'The Good Dinosaur',
 'Brave',
 'Star Trek Beyond',
 'WALL·E',
 'Rush Hour 3',
 '2012',
 'A Christmas Carol',
 'Jupiter Ascending',
 'The Legend of Tarzan',
 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
 'X-Men: Apocalypse',
 'The Dark Knight',
 'Up',
 'Monsters vs Aliens',
 'Iron Man',
 'Hugo',
 'Wild Wild West',
 'The Mummy: Tomb of the Dragon Emperor',
 'Suicide Squad',
 'Evan Almighty',
 'Edge of Tomorrow',
 'Waterworld',
 'G.I. Joe: The Rise of Cobra',
 'Inside Out',
 'The Jungle Book',
 'Iron Man 2',
 'Snow White and the Huntsman',
 'Maleficent',
 'Dawn of the Planet of the Apes',
 'The Lovers',
 '47 Ronin',
 'Captain America: The Winter Soldier',
 'Shrek Forever After',
 'Tomorrowland',
 'Big Hero 6',
 'Wreck-It Ralph',
 'The Polar Express',
 'Independence Day: Resurgence',
 'How to Train Your Dragon',
 'Terminator 3: Rise of the Machines',
 'Guardians of the Galaxy',
 'Interstellar',
 'Inception',
 'Shin Godzilla',
 'The Hobbit: An Unexpected Journey',
 'The Fast and the Furious',
 'The Curious Case of Benjamin Button',
 'X-Men: First Class',
 'The Hunger Games: Mockingjay - Part 2',
 "The Sorcerer's Apprentice",
 'Poseidon',
 'Alice Through the Looking Glass',
 'Shrek the Third',
 'Warcraft',
 'Terminator Genisys',
 'The Chronicles of Narnia: The Voyage of the Dawn Treader',
 'Pearl Harbor',
 'Transformers',
 'Alexander',
 'Harry Potter and the Order of the Phoenix',
 'Harry Potter and the Goblet of Fire',
 'Hancock',
 'I Am Legend',
 'Charlie and the Chocolate Factory',
 'Ratatouille',
 'Batman Begins',
 'Madagascar: Escape 2 Africa',
 'Night at the Museum: Battle of the Smithsonian',
 'X-Men Origins: Wolverine',
 'The Matrix Revolutions',
 'Frozen',
 'The Matrix Reloaded',
 'Thor: The Dark World',
 'Mad Max: Fury Road',
 'Angels & Demons',
 'Thor',
 'Bolt',
 'G-Force',
 'Wrath of the Titans',
 'Dark Shadows',
 'Mission: Impossible - Rogue Nation',
 'The Wolfman',
 'Bee Movie',
 'Kung Fu Panda 2',
 'The Last Airbender',
 'Mission: Impossible III',
 'White House Down',
 'Mars Needs Moms',
 'Flushed Away',
 'Pan',
 'Mr. Peabody & Sherman',
 'Troy',
 "Madagascar 3: Europe's Most Wanted",
 'Die Another Day',
 'Ghostbusters',
 'Armageddon',
 'Men in Black II',
 'Beowulf',
 'Kung Fu Panda 3',
 'Mission: Impossible - Ghost Protocol',
 'Rise of the Guardians',
 'Fun with Dick and Jane',
 'The Last Samurai',
 'Exodus: Gods and Kings',
 'Star Trek',
 'Spider-Man',
 'How to Train Your Dragon 2',
 'Gods of Egypt',
 'Stealth',
 'Watchmen',
 'Lethal Weapon 4',
 'Hulk',
 'G.I. Joe: Retaliation',
 'Sahara',
 'Final Fantasy: The Spirits Within',
 'Captain America: The First Avenger',
 'The World Is Not Enough',
 'Master and Commander: The Far Side of the World',
 'The Twilight Saga: Breaking Dawn - Part 2',
 'Happy Feet Two',
 'The Incredible Hulk',
 'The BFG',
 'The Revenant',
 'Turbo',
 'Rango',
 'Penguins of Madagascar',
 'The Bourne Ultimatum',
 'Kung Fu Panda',
 'Ant-Man',
 'The Hunger Games: Catching Fire',
 'Home',
 'War of the Worlds',
 'Bad Boys II',
 'Puss in Boots',
 'Salt',
 'Noah',
 'The Adventures of Tintin',
 'Harry Potter and the Prisoner of Azkaban',
 'Australia',
 'After Earth',
 'Dinosaur',
 'Night at the Museum: Secret of the Tomb',
 'Megamind',
 "Harry Potter and the Philosopher's Stone",
 'R.I.P.D.',
 'Pirates of the Caribbean: The Curse of the Black Pearl',
 'The Hunger Games: Mockingjay - Part 1',
 'The Da Vinci Code',
 'Rio 2',
 'X2',
 'Fast Five',
 'Sherlock Holmes: A Game of Shadows',
 'Clash of the Titans',
 'Total Recall',
 'The 13th Warrior',
 'The Bourne Legacy',
 'Batman & Robin',
 'How the Grinch Stole Christmas',
 'The Day After Tomorrow',
 'Mission: Impossible II',
 'The Perfect Storm',
 'Fantastic 4: Rise of the Silver Surfer',
 'Life of Pi',
 'Ghost Rider',
 'Jason Bourne',
 "Charlie's Angels: Full Throttle",
 'Prometheus',
 'Stuart Little 2',
 'Elysium',
 'The Chronicles of Riddick',
 'RoboCop',
 'Speed Racer',
 'How Do You Know',
 'Knight and Day',
 'Oblivion',
 'Star Wars: Episode III - Revenge of the Sith',
 'Star Wars: Episode II - Attack of the Clones',
 'Monsters, Inc.',
 'The Wolverine',
 'Star Wars: Episode I - The Phantom Menace',
 'The Croods',
 'Asterix at the Olympic Games',
 'Windtalkers',
 "The Huntsman: Winter's War",
 'Teenage Mutant Ninja Turtles',
 'Gravity',
 "Dante's Peak",
 'Teenage Mutant Ninja Turtles: Out of the Shadows',
 'Fantastic Four',
 'Night at the Museum',
 'San Andreas',
 'Tomorrow Never Dies',
 'The Patriot',
 "Ocean's Twelve",
 'Mr. & Mrs. Smith',
 'Insurgent',
 'The Aviator',
 "Gulliver's Travels",
 'The Green Hornet',
 '300: Rise of an Empire',
 'The Smurfs',
 'Home on the Range',
 'Allegiant',
 'Real Steel',
 'The Smurfs 2',
 'Speed 2: Cruise Control',
 "Ender's Game",
 'Live Free or Die Hard',
 'The Lord of the Rings: The Fellowship of the Ring',
 'Around the World in 80 Days',
 'Ali',
 'The Cat in the Hat',
 'I, Robot',
 'Kingdom of Heaven',
 'Stuart Little',
 'The Princess and the Frog',
 'The Martian',
 'The Island',
 'Town & Country',
 'Gone in Sixty Seconds',
 'Gladiator',
 'Minority Report',
 'Harry Potter and the Chamber of Secrets',
 'Casino Royale',
 'Planet of the Apes',
 'Terminator 2: Judgment Day',
 'Public Enemies',
 'American Gangster',
 'True Lies',
 'The Taking of Pelham 1 2 3',
 'Little Fockers',
 'The Other Guys',
 'Eraser',
 'Django Unchained',
 'The Hunchback of Notre Dame',
 "The Emperor's New Groove",
 'The Expendables 2',
 'National Treasure',
 'Eragon',
 'Where the Wild Things Are',
 'Epic',
 'The Tourist',
 'End of Days',
 'Blood Diamond',
 'The Wolf of Wall Street',
 'Batman Forever',
 'Starship Troopers',
 'Cloud Atlas',
 "Legend of the Guardians: The Owls of Ga'Hoole",
 'Catwoman',
 'Hercules',
 'Treasure Planet',
 'Land of the Lost',
 'The Expendables 3',
 'Point Break',
 'Son of the Mask',
 'In the Heart of the Sea',
 'The Adventures of Pluto Nash',
 'Green Zone',
 'The Peanuts Movie',
 'The Spanish Prisoner',
 'The Mummy Returns',
 'Gangs of New York',
 'The Flowers of War',
 "Surf's Up",
 'The Stepford Wives',
 'Black Hawk Down',
 'The Campaign',
 'The Fifth Element',
 'Sex and the City 2',
 'The Road to El Dorado',
 'Ice Age: Continental Drift',
 'Cinderella',
 'The Lovely Bones',
 'Finding Nemo',
 'The Lord of the Rings: The Return of the King',
 'The Lord of the Rings: The Two Towers',
 'Seventh Son',
 'Lara Croft: Tomb Raider',
 'Transcendence',
 'Jurassic Park III',
 'Rise of the Planet of the Apes',
 'The Spiderwick Chronicles',
 'A Good Day to Die Hard',
 'The Alamo',
 'The Incredibles',
 'Cutthroat Island',
 'Percy Jackson & the Olympians: The Lightning Thief',
 'Men in Black',
 'Toy Story 2',
 'Unstoppable',
 'Rush Hour 2',
 'What Lies Beneath',
 'Cloudy with a Chance of Meatballs',
 'Ice Age: Dawn of the Dinosaurs',
 'The Secret Life of Walter Mitty',
 "Charlie's Angels",
 'The Departed',
 'Mulan',
 'Tropic Thunder',
 'The Girl with the Dragon Tattoo',
 'Die Hard: With a Vengeance',
 'Sherlock Holmes',
 'Ben-Hur',
 'Atlantis: The Lost Empire',
 'Alvin and the Chipmunks: The Road Chip',
 'Valkyrie',
 "You Don't Mess with the Zohan",
 'Pixels',
 'A.I. Artificial Intelligence',
 'The Haunted Mansion',
 'Contact',
 'Hollow Man',
 'The Interpreter',
 'Percy Jackson: Sea of Monsters',
 'Lara Croft Tomb Raider: The Cradle of Life',
 'Now You See Me 2',
 'The Saint',
 'Spy Game',
 'Mission to Mars',
 'Rio',
 'Bicentennial Man',
 'Volcano',
 "The Devil's Own",
 'K-19: The Widowmaker',
 'Conan the Barbarian',
 'Cinderella Man',
 'The Nutcracker: The Untold Story',
 'Seabiscuit',
 'Twister',
 'Cast Away',
 'Happy Feet',
 'The Bourne Supremacy',
 'Air Force One',
 "Ocean's Eleven",
 'The Three Musketeers',
 'Hotel Transylvania',
 'Enchanted',
 'Safe House',
 '102 Dalmatians',
 'Tower Heist',
 'The Holiday',
 'Enemy of the State',
 "It's Complicated",
 "Ocean's Thirteen",
 'Open Season',
 'Divergent',
 'Enemy at the Gates',
 'The Rundown',
 'Last Action Hero',
 'Memoirs of a Geisha',
 'The Fast and the Furious: Tokyo Drift',
 'Arthur Christmas',
 'Meet Joe Black',
 'Collateral Damage',
 'All That Jazz',
 'Mirror Mirror',
 'Scott Pilgrim vs. the World',
 'The Core',
 'Nutty Professor II: The Klumps',
 'Scooby-Doo',
 'Dredd',
 'Click',
 'Creepshow',
 'Cats & Dogs 2 : The Revenge of Kitty Galore',
 'Jumper',
 'Hellboy II: The Golden Army',
 'Zodiac',
 'The 6th Day',
 'Bruce Almighty',
 'The Expendables',
 'Mission: Impossible',
 'The Hunger Games',
 'The Hangover Part II',
 'Batman Returns',
 'Over the Hedge',
 'Lilo & Stitch',
 "Charlotte's Web",
 'Deep Impact',
 'RED 2',
 'The Longest Yard',
 'Alvin and the Chipmunks: Chipwrecked',
 'Grown Ups 2',
 'Get Smart',
 "Something's Gotta Give",
 'Shutter Island',
 'Four Christmases',
 'Robots',
 'Face/Off',
 'Bedtime Stories',
 'Road to Perdition',
 'Just Go with It',
 'Con Air',
 'Eagle Eye',
 'Cold Mountain',
 'The Book of Eli',
 'Flubber',
 'The Haunting',
 'Space Jam',
 'The Pink Panther',
 'The Day the Earth Stood Still',
 'Conspiracy Theory',
 'Fury',
 'Six Days Seven Nights',
 'Yogi Bear',
 'Spirit: Stallion of the Cimarron',
 'Zookeeper',
 'Lost in Space',
 'The Manchurian Candidate',
 'Déjà Vu',
 'Hotel Transylvania 2',
 'Fantasia 2000',
 'The Time Machine',
 'Mighty Joe Young',
 'Swordfish',
 'The Legend of Zorro',
 'What Dreams May Come',
 'Little Nicky',
 'The Brothers Grimm',
 'Mars Attacks!',
 'Evolution',
 'The Edge',
 'Surrogates',
 'Thirteen Days',
 'Daylight',
 'Walking With Dinosaurs',
 'Battlefield Earth',
 'Looney Tunes: Back in Action',
 'Nine',
 'Timeline',
 'The Postman',
 'Babe: Pig in the City',
 'The Last Witch Hunter',
 'Red Planet',
 'Arthur and the Invisibles',
 'Oceans',
 'A Sound of Thunder',
 'Pompeii',
 'Top Cat Begins',
 'A Beautiful Mind',
 'The Lion King',
 'Journey 2: The Mysterious Island',
 'Cloudy with a Chance of Meatballs 2',
 'Red Dragon',
 'Hidalgo',
 'Jack and Jill',
 '2 Fast 2 Furious',
 'The Little Prince',
 'The Invasion',
 'The Adventures of Rocky & Bullwinkle',
 'The Secret Life of Pets',
 'The League of Extraordinary Gentlemen',
 'Despicable Me 2',
 'Independence Day',
 'The Lost World: Jurassic Park',
 'Madagascar',
 'Children of Men',
 'X-Men',
 'Wanted',
 'The Rock',
 'Ice Age: The Meltdown',
 '50 First Dates',
 'Hairspray',
 'Exorcist: The Beginning',
 'Inspector Gadget',
 'Now You See Me',
 'Grown Ups',
 'The Terminal',
 'Hotel for Dogs',
 'Vertical Limit',
 "Charlie Wilson's War",
 'Shark Tale',
 'Dreamgirls',
 'Be Cool',
 'Munich',
 'Tears of the Sun',
 'Killers',
 'The Man from U.N.C.L.E.',
 'Spanglish',
 'Monster House',
 'Bandits',
 'First Knight',
 'Anna and the King',
 'Immortals',
 'Hostage',
 'Titan A.E.',
 'Hollywood Homicide',
 'Soldier',
 'Carriers',
 'Monkeybone',
 'Flight of the Phoenix',
 'Unbreakable',
 'Minions',
 'Sucker Punch',
 'Snake Eyes',
 'Sphere',
 'The Angry Birds Movie',
 "Fool's Gold",
 'Funny People',
 'The Kingdom',
 'Talladega Nights: The Ballad of Ricky Bobby',
 'Dr. Dolittle 2',
 'Braveheart',
 'Jarhead',
 'The Simpsons Movie',
 'The Majestic',
 'Driven',
 'Two Brothers',
 'The Village',
 'Doctor Dolittle',
 'Signs',
 'Shrek 2',
 'Cars',
 'Runaway Bride',
 'xXx',
 'The SpongeBob Movie: Sponge Out of Water',
 'Ransom',
 'Inglourious Basterds',
 'Hook',
 'Die Hard 2',
 'S.W.A.T.',
 'Vanilla Sky',
 'Lady in the Water',
 'AVP: Alien vs. Predator',
 'Alvin and the Chipmunks: The Squeakquel',
 'We Were Soldiers',
 'Olympus Has Fallen',
 'Star Trek: Insurrection',
 'Battle: Los Angeles',
 'Big Fish',
 'Wolf',
 'War Horse',
 'The Monuments Men',
 'The Abyss',
 'Wall Street: Money Never Sleeps',
 'Dracula Untold',
 'The Siege',
 'Stardust',
 'Seven Years in Tibet',
 'The Dilemma',
 'Bad Company',
 'Doom',
 'I Spy',
 'Underworld: Awakening',
 'Rock of Ages',
 "Hart's War",
 'Killer Elite',
 'Rollerball',
 'Ballistic: Ecks vs. Sever',
 'Hard Rain',
 'Osmosis Jones',
 "Legends of Oz: Dorothy's Return",
 'Blackhat',
 'Sky Captain and the World of Tomorrow',
 'Basic Instinct 2',
 'Escape Plan',
 'The Legend of Hercules',
 'The Sum of All Fears',
 'The Twilight Saga: Eclipse',
 'The Score',
 'Despicable Me',
 'Money Train',
 'Ted 2',
 'Agora',
 'Mystery Men',
 'Hall Pass',
 'The Insider',
 'The Finest Hours',
 'Body of Lies',
 'Dinner for Schmucks',
 'Abraham Lincoln: Vampire Hunter',
 'Entrapment',
 'The X Files',
 'The Last Legion',
 'Saving Private Ryan',
 'Need for Speed',
 'What Women Want',
 'Ice Age',
 'Dreamcatcher',
 'Lincoln',
 'The Matrix',
 'Apollo 13',
 'The Santa Clause 2',
 'Les Misérables',
 "You've Got Mail",
 'Step Brothers',
 'The Mask of Zorro',
 'Due Date',
 'Unbroken',
 'Space Cowboys',
 'Cliffhanger',
 'Broken Arrow',
 'The Kid',
 'World Trade Center',
 'Mona Lisa Smile',
 'The Dictator',
 'Eyes Wide Shut',
 'Annie',
 'Focus',
 'This Means War',
 'Blade: Trinity',
 'Red Dawn',
 'Primary Colors',
 'Resident Evil: Retribution',
 'Death Race',
 'The Long Kiss Goodnight',
 'Proof of Life',
 'Zathura: A Space Adventure',
 'Fight Club',
 'We Are Marshall',
 'Hudson Hawk',
 'Lucky Numbers',
 'I, Frankenstein',
 'Oliver Twist',
 'Elektra',
 'Sin City: A Dame to Kill For',
 'Random Hearts',
 'Everest',
 'Perfume: The Story of a Murderer',
 'Austin Powers in Goldmember',
 'Astro Boy',
 'Jurassic Park',
 'Wyatt Earp',
 'Clear and Present Danger',
 'Dragon Blade',
 'Little Man',
 'U-571',
 'The American President',
 'The Love Guru',
 '3000 Miles to Graceland',
 'The Hateful Eight',
 'Blades of Glory',
 'Hop',
 '300',
 'Meet the Fockers',
 'Marley & Me',
 'The Green Mile',
 'Wild Hogs',
 'Chicken Little',
 'Gone Girl',
 'The Bourne Identity',
 'GoldenEye',
 "The General's Daughter",
 'The Truman Show',
 'The Prince of Egypt',
 'Daddy Day Care',
 '2 Guns',
 'Cats & Dogs',
 'The Italian Job',
 'Two Weeks Notice',
 'Antz',
 'Couples Retreat',
 'Days of Thunder',
 'Cheaper by the Dozen 2',
 'Maze Runner: The Scorch Trials',
 'Eat Pray Love',
 'The Family Man',
 'RED',
 'Any Given Sunday',
 'The Horse Whisperer',
 'Collateral',
 'The Scorpion King',
 'Ladder 49',
 'Jack Reacher',
 'Deep Blue Sea',
 'This Is It',
 'Contagion',
 'Kangaroo Jack',
 'Coraline',
 'The Happening',
 'Man on Fire',
 'The Shaggy Dog',
 'Starsky & Hutch',
 'Jingle All the Way',
 'Hellboy',
 'A Civil Action',
 'ParaNorman',
 'The Jackal',
 'Paycheck',
 'Up Close & Personal',
 'The Tale of Despereaux',
 'The Tuxedo',
 'Under Siege 2: Dark Territory',
 'Jack Ryan: Shadow Recruit',
 'Joy',
 'London Has Fallen',
 'Alien: Resurrection',
 'Shooter',
 'The Boxtrolls',
 'Practical Magic',
 'The Lego Movie',
 'Miss Congeniality 2: Armed and Fabulous',
 'Reign of Fire',
 'Gangster Squad',
 'Year One',
 'Invictus',
 'State of Play',
 'Duplicity',
 'My Favorite Martian',
 'The Sentinel',
 'Planet 51',
 'Star Trek: Nemesis',
 'Intolerable Cruelty',
 'Trouble with the Curve',
 'Edge of Darkness',
 'The Relic',
 'Analyze That',
 'Righteous Kill',
 'Mercury Rising',
 'The Soloist',
 'The Legend of Bagger Vance',
 'Almost Famous',
 'Garfield: A Tail of Two Kitties',
 'xXx: State of the Union',
 'Priest',
 'Sinbad: Legend of the Seven Seas',
 'Event Horizon',
 'Dragonfly',
 'The Black Dahlia',
 'Flyboys',
 'The Last Castle',
 'Supernova',
 "Winter's Tale",
 'The Mortal Instruments: City of Bones',
 'Meet Dave',
 'Dark Water',
 'Edtv',
 'Inkheart',
 'The Spirit',
 'Mortdecai',
 'In the Name of the King: A Dungeon Siege Tale',
 'Beyond Borders',
 'The Monkey King 2',
 'The Great Raid',
 'Deadpool',
 'Holy Man',
 'American Sniper',
 'Goosebumps',
 'Just Like Heaven',
 'The Flintstones in Viva Rock Vegas',
 'Rambo III',
 'Leatherheads',
 'The Ridiculous 6',
 'Did You Hear About the Morgans?',
 'The Internship',
 'Resident Evil: Afterlife',
 'Red Tails',
 "The Devil's Advocate",
 "That's My Boy",
 'DragonHeart',
 'After the Sunset',
 'Ghost Rider: Spirit of Vengeance',
 "Captain Corelli's Mandolin",
 'The Pacifier',
 'Walking Tall',
 'Forrest Gump',
 'Alvin and the Chipmunks',
 'Meet the Parents',
 'Pocahontas',
 'Superman',
 'The Nutty Professor',
 'Hitch',
 'George of the Jungle',
 'American Wedding',
 'Captain Phillips',
 'Date Night',
 'Casper',
 'The Equalizer',
 'Maid in Manhattan',
 'Crimson Tide',
 'The Pursuit of Happyness',
 'Flightplan',
 'Disclosure',
 'City of Angels',
 'Kill Bill: Vol. 1',
 'Bowfinger',
 'Kill Bill: Vol. 2',
 'Tango & Cash',
 'Death Becomes Her',
 'Shanghai Noon',
 'Executive Decision',
 "Mr. Popper's Penguins",
 'The Forbidden Kingdom',
 'Free Birds',
 'Alien³',
 'Evita',
 'Ronin',
 'The Ghost and the Darkness',
 'Paddington',
 'The Watch',
 'The Hunted',
 'Instinct',
 'Stuck on You',
 'Semi-Pro',
 'The Pirates! In an Adventure with Scientists!',
 'Changeling',
 'Chain Reaction',
 'The Fan',
 'The Phantom of the Opera',
 'Elizabeth: The Golden Age',
 'Æon Flux',
 'Gods and Generals',
 'Turbulence',
 'Imagine That',
 'Muppets Most Wanted',
 'Thunderbirds',
 'Burlesque',
 'A Very Long Engagement',
 'Lolita',
 'D-Tox',
 'Blade II',
 'Seven Pounds',
 'Bullet to the Head',
 'The Godfather: Part III',
 'Elizabethtown',
 'You, Me and Dupree',
 'Superman II',
 'Gigli',
 "All the King's Men",
 'Shaft',
 'Anastasia',
 'Moulin Rouge!',
 'Domestic Disturbance',
 'Black Mass',
 'Flags of Our Fathers',
 'Law Abiding Citizen',
 'Grindhouse',
 'Beloved',
 'Lucky You',
 'Catch Me If You Can',
 'Zero Dark Thirty',
 'The Break-Up',
 'Mamma Mia!',
 "Valentine's Day",
 'The Dukes of Hazzard',
 'The Thin Red Line',
 'The Change-Up',
 'Man on the Moon',
 'Casino',
 'From Paris with Love',
 'Bulletproof Monk',
 'Me, Myself & Irene',
 'Barnyard',
 'Deck the Halls',
 'The Twilight Saga: New Moon',
 'Shrek',
 'The Adjustment Bureau',
 'Robin Hood: Prince of Thieves',
 'Jerry Maguire',
 'Ted',
 'As Good as It Gets',
 'Patch Adams',
 'Anchorman 2: The Legend Continues',
 'Mr. Deeds',
 'Super 8',
 'Erin Brockovich',
 'How to Lose a Guy in 10 Days',
 '22 Jump Street',
 'Interview with the Vampire',
 'Yes Man',
 'Central Intelligence',
 'Stepmom',
 "Daddy's Home",
 'Into the Woods',
 'Inside Man',
 'Payback',
 'Congo',
 'We Bought a Zoo',
 'Knowing',
 'Failure to Launch',
 'The Ring Two',
 'Crazy, Stupid, Love.',
 'Garfield',
 'Christmas with the Kranks',
 'Moneyball',
 'Outbreak',
 'Non-Stop',
 'Race to Witch Mountain',
 'V for Vendetta',
 'Shanghai Knights',
 'Curious George',
 'Herbie Fully Loaded',
 "Don't Say a Word",
 'Hansel & Gretel: Witch Hunters',
 'Unfaithful',
 'I Am Number Four',
 'Syriana',
 '13 Hours: The Secret Soldiers of Benghazi',
 'The Book of Life',
 'Firewall',
 'Absolute Power',
 'G.I. Jane',
 'The Game',
 'Silent Hill',
 'The Replacements',
 'American Reunion',
 'The Negotiator',
 'Into the Storm',
 'Beverly Hills Cop III',
 'Gremlins 2: The New Batch',

* Now I have columns that I need for analysis. Now i am going to create new dataframe from this dataframe with movie_id,movie title & tags.

In [11]:
movies.isnull().sum()

movie_id        0
title           0
overview        3
genres          0
keywords        0
cast            0
crew            0
vote_count      0
vote_average    0
dtype: int64

* Handling Null and Duplicate values :

In [12]:
movies.dropna(inplace=True)

In [13]:
movies.duplicated().sum()

0

* Columns Normalisation :
  I observed that columns are in string format so i  have to convert themso i can use them in analysis

In [14]:
#1) Genres column:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [15]:
import ast
ast.literal_eval

In [16]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [17]:
movies['genres']=movies['genres'].apply(convert)

In [18]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew,vote_count,vote_average
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",11800,7.2

In [19]:
#2) Keywords column:
movies['keywords']=movies['keywords'].apply(convert)

In [20]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew,vote_count,vote_average
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",11800,7.2

In [21]:
#3) Cast columns:
    # for cast column i have to get names of three lead cast so I will create function based on above function for taht.

In [22]:
def convert_cast(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter += 1
        else:
            break
    return L

In [23]:
def convert3(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter += 1
        else:
            break

    return L

In [24]:

# Apply the function to the 'cast' column to create three new columns
movies[['cast1', 'cast2', 'cast3']] = movies['cast'].apply(convert_cast).apply(pd.Series)

C:\Users\DELL\AppData\Local\Temp\ipykernel_6784\1107788568.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  movies[['cast1', 'cast2', 'cast3']] = movies['cast'].apply(convert_cast).apply(pd.Series)

In [25]:
movies['cast']=movies['cast'].apply(convert3)

In [26]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew,vote_count,vote_average,cast1,cast2,cast3
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",11800,7.2,Sam Worthington,Zoe Saldana,Sigourney Weaver

In [27]:
#4) Crew column:
   #in this i obsverved that there are multiple dictionaries soi have extract the director name from job dictionary.So i will create new function based on above filter

In [28]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [29]:
movies['crew']=movies['crew'].apply(fetch_director)

In [30]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew,vote_count,vote_average,cast1,cast2,cast3
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],11800,7.2,Sam Worthington,Zoe Saldana,Sigourney Weaver

In [31]:
#5) overview column: this is string column now i will convert it in list

In [32]:
movies['overview']= movies['overview'].apply(lambda x:x.split())

In [33]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew,vote_count,vote_average,cast1,cast2,cast3
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],11800,7.2,Sam Worthington,Zoe Saldana,Sigourney Weaver
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],4500,6.9,Johnny Depp,Orlando Bloom,Keira Knightley

In [34]:
mov=movies.copy()

In [35]:
mov

,movie_id,title,overview,genres,keywords,cast,crew,vote_count,vote_average,cast1,cast2,cast3
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],11800,7.2,Sam Worthington,Zoe Saldana,Sigourney Weaver
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],4500,6.9,Johnny Depp,Orlando Bloom,Keira Knightley
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],4466,6.3,Daniel Craig,Christoph Waltz,Léa Seydoux
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],9106,7.6,Christian Bale,Michael Caine,Gary Oldman
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],2124,6.1,Taylor Kitsch,Lynn Collins,Samantha Morton
...,...,...,...,...,...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, pap...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez],238,6.6,Carlos Gallardo,Jaime de Hoyos,Peter Marquardt
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]",[],"[Edward Burns, Kerry Bishé, Marsha Dietlein]",[Edward Burns],5,5.9,Edward Burns,Kerry Bishé,Marsha Dietlein
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","[Eric Mabius, Kristin Booth, Crystal Lowe]",[Scott Smith],6,7.0,Eric Mabius,Kristin Booth,Crystal Lowe
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[],[],"[Daniel Henney, Eliza Coupe, Bill Paxton]",[Daniel Hsia],7,5.7,Daniel Henney,Eliza Coupe,Bill Paxton
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[obsession, camcorder, crush, dream girl]","[Drew Barrymore, Brian Herzlinger, Corey Feldman]",[Brian Herzlinger],16,6.3,Drew Barrymore,Brian Herzlinger,Corey Feldman

* In this dataset we have to remove space so that same names/words does not clash with other words which can cause confusion.

In [36]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [37]:
movies=movies.rename(columns={'crew': 'Director'})

In [38]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,Director,vote_count,vote_average,cast1,cast2,cast3
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],11800,7.2,Sam Worthington,Zoe Saldana,Sigourney Weaver
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],4500,6.9,Johnny Depp,Orlando Bloom,Keira Knightley

* Now I am creating new column named tags.

In [39]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['Director']

In [40]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,Director,vote_count,vote_average,cast1,cast2,cast3,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],11800,7.2,Sam Worthington,Zoe Saldana,Sigourney Weaver,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],4500,6.9,Johnny Depp,Orlando Bloom,Keira Knightley,"[Captain, Barbossa,, long, believed, to, be, d..."

In [41]:
new_df=movies[['movie_id','title','tags']]

In [42]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [43]:
new_df['tags']= new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\DELL\AppData\Local\Temp\ipykernel_6784\335926201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']= new_df['tags'].apply(lambda x:" ".join(x))

In [44]:
new_df

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...

In [45]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [46]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\DELL\AppData\Local\Temp\ipykernel_6784\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [47]:
new_df

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,a newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,when ambitious new york attorney sam is sent t...
4808,25975,My Date with Drew,ever since the second grade when he first saw ...

* In tags column i see that some words are repeating so i have to handle that.

In [48]:
import nltk

In [49]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [50]:
def stem(text):
    y=[]
    
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [51]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\DELL\AppData\Local\Temp\ipykernel_6784\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

* Text Vectorisation :

In [52]:
from sklearn.feature_extraction.text  import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words= 'english')

In [53]:
vectors= cv.fit_transform(new_df['tags']).toarray()

In [54]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [55]:
cv.get_feature_names()

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcatraz',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrysonnenfeld',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'basketball',
 'bat',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blame',
 'blend',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'bout',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brainwash',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breast',
 'breath',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryansing',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'canuxploit',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciaránhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collis',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compuls',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'connel',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convict',
 'convinc',
 'cook',
 ...]

In [56]:
from sklearn.metrics.pairwise import cosine_similarity

In [57]:
similarity=cosine_similarity(vectors)

In [58]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(1216, 0.28676966733820225),
 (2409, 0.26901379342448517),
 (3730, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.25038669783359574)]

# movies recommendation on title -:

In [59]:
def recommend(movie):
    movie_index= new_df[new_df['title']==movie].index[0]
    distances= similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    recommended_movies = []
    for i in movies_list:
        recommended_movies.append(new_df.iloc[i[0]].title)
    return recommended_movies

In [60]:
recommend('Batman Begins')

['The Dark Knight', 'Batman', 'Batman', 'The Dark Knight Rises', '10th & Wolf']

#  Movies based on Rating -:

In [61]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,Director,vote_count,vote_average,cast1,cast2,cast3,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],11800,7.2,Sam Worthington,Zoe Saldana,Sigourney Weaver,"[In, the, 22nd, century,, a, paraplegic, Marin..."

movie recommendation based on ratings:

In [62]:
c=np.mean(movies['vote_average'])

In [63]:
c

6.093258426966287

In [64]:
m= np.quantile(movies['vote_count'],0.1)

In [65]:
m

12.0

In [66]:
q_movies = movies.copy().loc[movies['vote_count'] >= m]
q_movies.shape

(4331, 13)

In [67]:
def weighted_rating(x, m=m, c=c):
    v = x['vote_count']
    R = x['vote_average']
    # Calculation based on the IMDB formula
    return (v/(v+m) * R) + (m/(m+v) * c)

In [68]:
# Define a new feature 'score' and calculate its value with `weighted_rating()`
q_movies['score'] = q_movies.apply(weighted_rating, axis=1).astype('int')

In [69]:
#Sort movies based on score calculated above
q_movies = q_movies.sort_values('score', ascending=False)

#Print the top 15 movies
q_movies[['title', 'vote_count', 'vote_average', 'score']].head(10)

                       title  vote_count  vote_average  score
2253       Princess Mononoke        1983           8.2      8
2737  The Godfather: Part II        3338           8.3      8
95              Interstellar       10867           8.1      8
4245            Modern Times         856           8.1      8
3913           The Apartment         483           8.1      8
662               Fight Club        9413           8.3      8
809             Forrest Gump        7927           8.2      8
96                 Inception       13752           8.1      8
1824        Schindler's List        4329           8.3      8
3459      The Usual Suspects        3254           8.1      8

movies based onn geres

In [70]:
q_movies[q_movies['score']==5][['title','genres','cast','Director','score']]

,title,genres,cast,Director,score
476,Surrogates,"[Action, ScienceFiction, Thriller]","[BruceWillis, RadhaMitchell, RosamundPike]",[JonathanMostow],5
478,Daylight,"[Action, Adventure, Thriller]","[SylvesterStallone, AmyBrenneman, ViggoMortensen]",[RobCohen],5
502,The Invasion,"[ScienceFiction, Thriller]","[NicoleKidman, DanielCraig, JeremyNortham]",[OliverHirschbiegel],5
3896,Paranormal Activity 2,"[Horror, Thriller]","[KatieFeatherston, DavidBierend, BrianBoland]",[TodWilliams],5
1667,Antitrust,"[Action, Crime, Drama]","[RyanPhillippe, RachaelLeighCook, TimRobbins]",[PeterHowitt],5
...,...,...,...,...,...
3304,Swelter,"[Action, Drama, Thriller]","[Jean-ClaudeVanDamme, BradCarter, JoshHenderson]",[KeithParmer],5
3302,The Death and Life of Bobby Z,"[Drama, Action, Thriller, Crime]","[PaulWalker, LaurenceFishburne, OliviaWilde]",[JohnHerzfeld],5
1590,Like Mike,"[Comedy, Drama, Family, Fantasy]","[ShadMoss, MorrisChestnut, JonathanLipnicki]",[JohnSchultz],5
3300,Aloft,[Drama],"[JenniferConnelly, MélanieLaurent, CillianMurphy]",[ClaudiaLlosa],5
1413,House of Wax,[Horror],"[ElishaCuthbert, ParisHilton, BrianVanHolt]",[JaumeCollet-Serra],5

In [71]:
q_movies['score'].unique()

array([8, 7, 6, 5, 4, 3, 2])

In [72]:
q_movies[q_movies['title']=='Avatar']['score']

0    7
Name: score, dtype: int32

In [73]:
def rating (df,rating):
    a=df[df['score'] == rating][['title', 'genres', 'cast', 'Director', 'score']]
    return a

In [74]:
rating(q_movies,8)

,title,genres,cast,Director,score
2253,Princess Mononoke,"[Adventure, Fantasy, Animation]","[YōjiMatsuda, YurikoIshida, YūkoTanaka]",[HayaoMiyazaki],8
2737,The Godfather: Part II,"[Drama, Crime]","[AlPacino, RobertDuvall, DianeKeaton]",[FrancisFordCoppola],8
95,Interstellar,"[Adventure, Drama, ScienceFiction]","[MatthewMcConaughey, JessicaChastain, AnneHath...",[ChristopherNolan],8
4245,Modern Times,"[Drama, Comedy]","[CharlieChaplin, PauletteGoddard, HenryBergman]",[CharlieChaplin],8
3913,The Apartment,"[Comedy, Drama, Romance]","[JackLemmon, ShirleyMacLaine, FredMacMurray]",[BillyWilder],8
662,Fight Club,[Drama],"[EdwardNorton, BradPitt, MeatLoaf]",[DavidFincher],8
809,Forrest Gump,"[Comedy, Drama, Romance]","[TomHanks, RobinWright, GarySinise]",[RobertZemeckis],8
96,Inception,"[Action, Thriller, ScienceFiction, Mystery, Ad...","[LeonardoDiCaprio, JosephGordon-Levitt, EllenP...",[ChristopherNolan],8
1824,Schindler's List,"[Drama, History, War]","[LiamNeeson, BenKingsley, RalphFiennes]",[StevenSpielberg],8
3459,The Usual Suspects,"[Drama, Crime, Thriller]","[StephenBaldwin, GabrielByrne, ChazzPalminteri]",[BryanSinger],8
1559,Se7en,"[Crime, Mystery, Thriller]","[BradPitt, MorganFreeman, GwynethPaltrow]",[DavidFincher],8
4308,"The Good, the Bad and the Ugly",[Western],"[EliWallach, ClintEastwood, LeeVanCleef]",[SergioLeone],8
4608,12 Angry Men,[Drama],"[HenryFonda, MartinBalsam, JohnFiedler]",[SidneyLumet],8
65,The Dark Knight,"[Drama, Action, Crime, Thriller]","[ChristianBale, HeathLedger, AaronEckhart]",[ChristopherNolan],8
2176,Psycho,"[Drama, Horror, Thriller]","[AnthonyPerkins, VeraMiles, JohnGavin]",[AlfredHitchcock],8
3342,The Godfather,"[Drama, Crime]","[MarlonBrando, AlPacino, JamesCaan]",[FrancisFordCoppola],8
3062,American History X,[Drama],"[EdwardNorton, EdwardFurlong, BeverlyD'Angelo]",[TonyKaye],8
2097,The Silence of the Lambs,"[Crime, Drama, Thriller]","[JodieFoster, AnthonyHopkins, ScottGlenn]",[JonathanDemme],8
3726,One Flew Over the Cuckoo's Nest,[Drama],"[JackNicholson, LouiseFletcher, DannyDeVito]",[MilošForman],8
2766,Room,"[Drama, Thriller]","[BrieLarson, JacobTremblay, JoanAllen]",[LennyAbrahamson],8
3578,Memento,"[Mystery, Thriller]","[GuyPearce, Carrie-AnneMoss, JoePantoliano]",[ChristopherNolan],8
4541,Seven Samurai,"[Action, Drama]","[ToshirōMifune, TakashiShimura, YoshioInaba]",[AkiraKurosawa],8
3627,Once Upon a Time in the West,[Western],"[HenryFonda, ClaudiaCardinale, JasonRobards]",[SergioLeone],8
1993,Howl's Moving Castle,"[Fantasy, Animation, Adventure]","[TakuyaKimura, AkihiroMiwa, TatsuyaGashûin]",[HayaoMiyazaki],8
3872,Whiplash,[Drama],"[MilesTeller, J.K.Simmons, MelissaBenoist]",[DamienChazelle],8
1853,GoodFellas,"[Drama, Crime]","[RobertDeNiro, RayLiotta, JoePesci]",[MartinScorsese],8
1887,The Shawshank Redemption,"[Drama, Crime]","[TimRobbins, MorganFreeman, BobGunton]",[FrankDarabont],8
2459,Dead Poets Society,[Drama],"[RobinWilliams, EthanHawke, RobertSeanLeonard]",[PeterWeir],8
1669,Once Upon a Time in America,"[Drama, Crime]","[RobertDeNiro, JamesWoods, ElizabethMcGovern]",[SergioLeone],8
3873,City of God,"[Drama, Crime]","[AlexandreRodrigues, LeandroFirmino, PhellipeH...",[FernandoMeirelles],8
329,The Lord of the Rings: The Return of the King,"[Adventure, Fantasy, Action]","[ElijahWood, IanMcKellen, ViggoMortensen]",[PeterJackson],8
2917,Star Wars,"[Adventure, Action, ScienceFiction]","[MarkHamill, HarrisonFord, CarrieFisher]",[GeorgeLucas],8
1996,The Empire Strikes Back,"[Adventure, Action, ScienceFiction]","[MarkHamill, HarrisonFord, CarrieFisher]",[IrvinKershner],8
690,The Green Mile,"[Fantasy, Drama, Crime]","[TomHanks, MichaelClarkeDuncan, DavidMorse]",[FrankDarabont],8
2290,The Shining,"[Horror, Thriller]","[JackNicholson, ShelleyDuvall, DannyLloyd]",[StanleyKubrick],8
3237,Pulp Fiction,"[Thriller, Crime]","[JohnTravolta, SamuelL.Jackson, UmaThurman]",[QuentinTarantino],8
2300,Spirited Away,"[Fantasy, Adventure, Animation, Family]","[RumiHiiragi, MiyuIrino, MariNatsuki]",[HayaoMiyazaki],8

In [75]:
q_movies[q_movies['score'] == 8][['title', 'genres', 'cast', 'Director', 'score']].head(10)

,title,genres,cast,Director,score
2253,Princess Mononoke,"[Adventure, Fantasy, Animation]","[YōjiMatsuda, YurikoIshida, YūkoTanaka]",[HayaoMiyazaki],8
2737,The Godfather: Part II,"[Drama, Crime]","[AlPacino, RobertDuvall, DianeKeaton]",[FrancisFordCoppola],8
95,Interstellar,"[Adventure, Drama, ScienceFiction]","[MatthewMcConaughey, JessicaChastain, AnneHath...",[ChristopherNolan],8
4245,Modern Times,"[Drama, Comedy]","[CharlieChaplin, PauletteGoddard, HenryBergman]",[CharlieChaplin],8
3913,The Apartment,"[Comedy, Drama, Romance]","[JackLemmon, ShirleyMacLaine, FredMacMurray]",[BillyWilder],8
662,Fight Club,[Drama],"[EdwardNorton, BradPitt, MeatLoaf]",[DavidFincher],8
809,Forrest Gump,"[Comedy, Drama, Romance]","[TomHanks, RobinWright, GarySinise]",[RobertZemeckis],8
96,Inception,"[Action, Thriller, ScienceFiction, Mystery, Ad...","[LeonardoDiCaprio, JosephGordon-Levitt, EllenP...",[ChristopherNolan],8
1824,Schindler's List,"[Drama, History, War]","[LiamNeeson, BenKingsley, RalphFiennes]",[StevenSpielberg],8
3459,The Usual Suspects,"[Drama, Crime, Thriller]","[StephenBaldwin, GabrielByrne, ChazzPalminteri]",[BryanSinger],8

In [114]:
q_movies.head(1)

,movie_id,title,overview,genres,keywords,cast,Director,vote_count,vote_average,cast1,cast2,cast3,tags,score
2253,128,Princess Mononoke,"[Ashitaka,, a, prince, of, the, disappearing, ...","[Adventure, Fantasy, Animation]","[fight, wolf, villageandtown, iron, pan, wildb...","[YōjiMatsuda, YurikoIshida, YūkoTanaka]",[HayaoMiyazaki],1983,8.2,Yōji Matsuda,Yuriko Ishida,Yūko Tanaka,"[Ashitaka,, a, prince, of, the, disappearing, ...",8

In [158]:
def rating_recommended(rating, q_movies, similarity):
    # Check if any movies are available for the specified director

    movie_index=  q_movies[q_movies['score']==rating].index.tolist()[:10]
    distances= similarity[movie_index]
    movies_list=movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: np.allclose(distances, x[1]))[1:11]
    
    genrewise_movies = q_movies.iloc[[i[0] for i in movies_list]][['title', 'genres', 'cast', 'Director']]

    return genrewise_movies

In [159]:
q_movies[q_movies['score'] == 6].index.tolist()[:10]

[2499, 4347, 2794, 2508, 2795, 4478, 2494, 2504, 2495, 2496]

In [160]:
rating_recommended('6', q_movies, similarity)

Empty DataFrame
Columns: [title, genres, cast, Director]
Index: []

In [175]:
def rating_recommendation(rating,q_movies,similarity):
    movie_index=  q_movies[q_movies['score']==6].index.tolist()[:10]
    distances= similarity[np.array(movie_index)]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: np.allclose(distances, x[1]))[1:11]
    genrewise_movies = q_movies.iloc[[i[0] for i in movies_list]][['title', 'genres', 'cast', 'Director','score']]
    return genrewise_movies

In [165]:
movie_index=  q_movies[q_movies['score']==6].index.tolist()[:10]

movie_index

[2499, 4347, 2794, 2508, 2795, 4478, 2494, 2504, 2495, 2496]

In [176]:
rating_recommendation('6',q_movies,similarity)

,title,genres,cast,Director,score
2737,The Godfather: Part II,"[Drama, Crime]","[AlPacino, RobertDuvall, DianeKeaton]",[FrancisFordCoppola],8
95,Interstellar,"[Adventure, Drama, ScienceFiction]","[MatthewMcConaughey, JessicaChastain, AnneHath...",[ChristopherNolan],8
4245,Modern Times,"[Drama, Comedy]","[CharlieChaplin, PauletteGoddard, HenryBergman]",[CharlieChaplin],8
3913,The Apartment,"[Comedy, Drama, Romance]","[JackLemmon, ShirleyMacLaine, FredMacMurray]",[BillyWilder],8
662,Fight Club,[Drama],"[EdwardNorton, BradPitt, MeatLoaf]",[DavidFincher],8
809,Forrest Gump,"[Comedy, Drama, Romance]","[TomHanks, RobinWright, GarySinise]",[RobertZemeckis],8
96,Inception,"[Action, Thriller, ScienceFiction, Mystery, Ad...","[LeonardoDiCaprio, JosephGordon-Levitt, EllenP...",[ChristopherNolan],8
1824,Schindler's List,"[Drama, History, War]","[LiamNeeson, BenKingsley, RalphFiennes]",[StevenSpielberg],8
3459,The Usual Suspects,"[Drama, Crime, Thriller]","[StephenBaldwin, GabrielByrne, ChazzPalminteri]",[BryanSinger],8

In [148]:
distances= similarity[movie_index]
distances

array([[0.0270369 , 0.0571662 , 0.        , ..., 0.09245003, 0.02380952,
        0.02541643],
       [0.        , 0.06482037, 0.03340766, ..., 0.02620712, 0.02699746,
        0.        ],
       [0.05263158, 0.02782074, 0.02867697, ..., 0.06748819, 0.11587244,
        0.09895414],
       ...,
       [0.0338255 , 0.        , 0.03686049, ..., 0.05783149, 0.        ,
        0.        ],
       [0.02533473, 0.        , 0.        , ..., 0.0216574 , 0.        ,
        0.        ],
       [0.14119562, 0.08956222, 0.12309149, ..., 0.        , 0.22381413,
        0.10618637]])

In [153]:
movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: np.allclose(distances, x[1]))[1:11]
movies_list

[(1,
  array([0.        , 0.06482037, 0.03340766, ..., 0.02620712, 0.02699746,
         0.        ])),
 (2,
  array([0.05263158, 0.02782074, 0.02867697, ..., 0.06748819, 0.11587244,
         0.09895414])),
 (3,
  array([0.        , 0.03363364, 0.06933752, ..., 0.02719641, 0.05603318,
         0.02990743])),
 (4,
  array([0.05735393, 0.03031695, 0.0625    , ..., 0.02451452, 0.        ,
         0.05391639])),
 (5,
  array([0.        , 0.04776973, 0.03282661, ..., 0.02575131, 0.18569534,
         0.16990964])),
 (6,
  array([0.        , 0.02501564, 0.        , ..., 0.04045567, 0.08335142,
         0.04448841])),
 (7,
  array([0.0338255 , 0.        , 0.03686049, ..., 0.05783149, 0.        ,
         0.        ])),
 (8,
  array([0.02533473, 0.        , 0.        , ..., 0.0216574 , 0.        ,
         0.        ])),
 (9,
  array([0.14119562, 0.08956222, 0.12309149, ..., 0.        , 0.22381413,
         0.10618637]))]

In [157]:
genrewise_movies = q_movies.iloc[[i[0] for i in movies_list]][['title', 'genres', 'cast', 'Director']]
genrewise_movies

,title,genres,cast,Director
2737,The Godfather: Part II,"[Drama, Crime]","[AlPacino, RobertDuvall, DianeKeaton]",[FrancisFordCoppola]
95,Interstellar,"[Adventure, Drama, ScienceFiction]","[MatthewMcConaughey, JessicaChastain, AnneHath...",[ChristopherNolan]
4245,Modern Times,"[Drama, Comedy]","[CharlieChaplin, PauletteGoddard, HenryBergman]",[CharlieChaplin]
3913,The Apartment,"[Comedy, Drama, Romance]","[JackLemmon, ShirleyMacLaine, FredMacMurray]",[BillyWilder]
662,Fight Club,[Drama],"[EdwardNorton, BradPitt, MeatLoaf]",[DavidFincher]
809,Forrest Gump,"[Comedy, Drama, Romance]","[TomHanks, RobinWright, GarySinise]",[RobertZemeckis]
96,Inception,"[Action, Thriller, ScienceFiction, Mystery, Ad...","[LeonardoDiCaprio, JosephGordon-Levitt, EllenP...",[ChristopherNolan]
1824,Schindler's List,"[Drama, History, War]","[LiamNeeson, BenKingsley, RalphFiennes]",[StevenSpielberg]
3459,The Usual Suspects,"[Drama, Crime, Thriller]","[StephenBaldwin, GabrielByrne, ChazzPalminteri]",[BryanSinger]

In [192]:
q_movies[q_movies['score']==6].index.tolist()[:10]

[2499, 4347, 2794, 2508, 2795, 4478, 2494, 2504, 2495, 2496]

In [188]:
q_movies['score'].unique().astype('int')

array([8, 7, 6, 5, 4, 3, 2])

In [181]:
q_movies.head(1)

,movie_id,title,overview,genres,keywords,cast,Director,vote_count,vote_average,cast1,cast2,cast3,tags,score
2253,128,Princess Mononoke,"[Ashitaka,, a, prince, of, the, disappearing, ...","[Adventure, Fantasy, Animation]","[fight, wolf, villageandtown, iron, pan, wildb...","[YōjiMatsuda, YurikoIshida, YūkoTanaka]",[HayaoMiyazaki],1983,8.2,Yōji Matsuda,Yuriko Ishida,Yūko Tanaka,"[Ashitaka,, a, prince, of, the, disappearing, ...",8

In [136]:
movie_index

Int64Index([2499, 4347, 2794, 2508, 2795, 4478, 2494, 2504, 2495, 2496,
            ...
            1672, 1621, 1889, 1640, 1893, 1869, 1623, 1624, 1424, 1689],
           dtype='int64', length=2080)

# Movies Based on actors

* Actors Movies -:

In [76]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,Director,vote_count,vote_average,cast1,cast2,cast3,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],11800,7.2,Sam Worthington,Zoe Saldana,Sigourney Weaver,"[In, the, 22nd, century,, a, paraplegic, Marin..."

In [77]:

cast_columns = ['cast1', 'cast2', 'cast3']
actors = set(str(actor) for col in cast_columns for actor in movies[col].fillna(''))
sorted_actors = sorted(actors)

In [78]:
sorted_actors.insert(0,'Overall')

In [79]:
sorted_actors

['Overall',
 '',
 '"Weird Al" Yankovic',
 '50 Cent',
 'A.J. Buckley',
 'A.J. Cook',
 'A.J. DeLucia',
 'AJ Michalka',
 'Aaliyah',
 'Aamir Khan',
 'Aaran Thomas',
 'Aaron Abrams',
 'Aaron Eckhart',
 'Aaron Kwok',
 'Aaron Paul',
 'Aaron Ruell',
 'Aaron Stanford',
 'Aaron Taylor-Johnson',
 'Aaron Yoo',
 'Aasheekaa Bathija',
 'Aasif Mandvi',
 'Abbey Lincoln',
 'Abbie Cornish',
 'Abhinay Vaddi',
 'Abhishek Bachchan',
 'Abigail Breslin',
 'Abigail Hargrove',
 'Abigail Spencer',
 'Ace Marrero',
 'Adam Baldwin',
 'Adam Beach',
 'Adam Bousdoukos',
 'Adam Brody',
 'Adam Brooks',
 'Adam Butcher',
 'Adam Campbell',
 'Adam Carolla',
 'Adam Clayton',
 'Adam Driver',
 'Adam G. Sevani',
 'Adam Garcia',
 'Adam Goldberg',
 'Adam Greaves-Neal',
 'Adam Lamberg',
 'Adam Levine',
 'Adam Pascal',
 'Adam Rayner',
 'Adam Rifkin',
 'Adam Rodríguez',
 'Adam Sandler',
 'Adam Scott',
 'Adam Trese',
 'Adam West',
 'Adar Beck',
 'Adelaide Clemens',
 'Adele Mara',
 'Adewale Akinnuoye-Agbaje',
 'Adil Koukouh',
 'Adolfo Celi',
 'Adolph Davis',
 'Adolphe Menjou',
 'Adrian Dunbar',
 'Adrian Gaeta',
 'Adrian Gonzalez',
 'Adrian Grenier',
 'Adrian James',
 'Adrian Paul',
 'Adriana Barraza',
 'Adriana Caselotti',
 'Adrianne Palicki',
 'Adriano Giannini',
 'Adrien Brody',
 'Adrienne Barbeau',
 'Adrienne King',
 'Adrienne Pickering',
 'Adrián Alonso Barona',
 'Agata Kulesza',
 'Agata Trzebuchowska',
 'Agnes Bruckner',
 'Agniya Ditkovskite',
 'Ahn Sung-Ki',
 'Ahnaise Christmas',
 'Aidan Devine',
 'Aidan Gillen',
 'Aidan McArdle',
 'Aidan Quinn',
 'Aimee Garcia',
 'Aimee Teegarden',
 'Aishwarya Rai Bachchan',
 'Aislinn Derbez',
 'Aitana Sánchez-Gijón',
 'Aja Naomi King',
 'Akihiro Miwa',
 'Akiko Wakabayashi',
 'Aksel Hennie',
 'Akshay Kumar',
 'Akshaye Khanna',
 'Al Bandiero',
 'Al Gore',
 'Al Pacino',
 'Alain Moussi',
 'Alakina Mann',
 'Alan Alda',
 'Alan Arkin',
 'Alan Bates',
 'Alan Bean',
 'Alan Cox',
 'Alan Cumming',
 'Alan King',
 'Alan Rickman',
 'Alan Tudyk',
 'Alan van Sprang',
 'Albert Brooks',
 'Albert Dupontel',
 'Albert Finney',
 'Albert Hall',
 'Alberto San Juan',
 'Alden Ehrenreich',
 'Alec Baldwin',
 'Alec Guinness',
 'Alec McCowen',
 'Aleisha Allen',
 'Aleisha Force',
 'Aleksandr Robak',
 'Aleksey Chadov',
 'Alessandro Gassman',
 'Alessandro Nivola',
 'Alessandro Preziosi',
 'Alex Anfanger',
 'Alex Borstein',
 'Alex Briley',
 'Alex D. Linz',
 'Alex Karpovsky',
 'Alex Kendrick',
 'Alex Lawther',
 'Alex Michaeletos',
 "Alex O'Loughlin",
 'Alex Petrovitch',
 'Alex Pettyfer',
 'Alex Reid',
 'Alex Rocco',
 'Alex Roe',
 'Alex Russell',
 'Alex Veadov',
 'Alex Vincent',
 'Alex Winter',
 'Alexa Nikolas',
 'Alexa PenaVega',
 'Alexander G. Eckert',
 'Alexander Godunov',
 'Alexander Gould',
 'Alexander Karim',
 'Alexander Ludwig',
 'Alexander Polinsky',
 'Alexander Pollock',
 'Alexander Scheer',
 'Alexander Siddig',
 'Alexander Skarsgård',
 'Alexandra Daddario',
 'Alexandra Maria Lara',
 'Alexandra Rapaport',
 'Alexandre Rodrigues',
 'Alexie Gilmore',
 'Alexis Bledel',
 'Alexis Georgoulis',
 'Alexis Kendra',
 'Alfie Allen',
 'Alfre Woodard',
 'Alfred Abel',
 'Alfred Molina',
 'Ali Cobrin',
 'Ali Fadhil',
 'Ali Kazim',
 'Ali Landry',
 'Ali Larter',
 'Alia Shawkat',
 'Alice Braga',
 'Alice Englert',
 'Alice Evans',
 'Alice Eve',
 'Alice Faye',
 'Alice Garner',
 'Alice Parkinson',
 'Alice Patten',
 'Alice Pol',
 'Alicia Mendez',
 'Alicia Silverstone',
 'Alicia Vikander',
 'Alicia Witt',
 'Alicja Bachleda-Curuś',
 'Aliou Touré',
 'Alison Brie',
 'Alison Lohman',
 'Alison Monda',
 'Alison Raimondi',
 'Allan Bryan Weku',
 'Allan Corduner',
 'Allan Gildea',
 'Allen Covert',
 'Allen Danziger',
 'Allen Fiuzat',
 'Allen Joseph',
 'Allen Payne',
 'Allie Mickelson',
 'Allison Egan',
 'Allison Janney',
 'Allison Miller',
 'Allison Paige',
 'Allison Tolman',
 'Ally Sheedy',
 'Allyson Sereboff',
 'Alonna Shaw',
 'Aly Michalka',
 'Alyson Hannigan',
 'Alyssa Milano',
 'Amancaya Aguilar',
 'Amanda Bynes',
 'Amanda Crew',
 'Amanda Peet',
 'Amanda Plummer',
 'Amanda Schull',
 'Amanda Seyfried',
 'Amanda Tapping',
 'Amara Miller',
 'Amber Heard',
 'Amber Marie Bollinger',
 'Amber Tamblyn',
 'Amber Valletta',
 'America Ferrera',
 'America Olivo',
 'Ami Ayalon',
 'Amie Petersen',
 'Amir Farrokh Hashemian',
 'Amitabh Bachchan',
 'Amos Oz',
 'Amy Acker',
 'Amy Adams',
 'Amy Badberg',
 'Amy Brenneman',
 'Amy Carson',
 'Amy Hargreaves',
 'Amy Hathaway',
 'Amy Irving',
 'Amy Poehler',
 'Amy Ryan',
 'Amy Schumer',
 'Amy Smart',
 'Amy Steel',
 'Amy Stewart',
 'Ana Claudia Talancón',
 'Ana Coto',
 'Ana Maria Guran',
 'Ana Wagener',
 'Ana de la Reguera',
 'Analeigh Tipton',
 'Anamaria Marinca',
 'Andie MacDowell',
 'Andre Braugher',
 'Andrea Brooks',
 'Andrea Eckert',
 'Andrea Edmondson',
 'Andrea Vergara',
 'Andree Maranda',
 'Andree Moss',
 'Andrew Bujalski',
 'Andrew Caldwell',
 'Andrew Dice Clay',
 'Andrew Garfield',
 'Andrew J. West',
 'Andrew Jacobs',
 'Andrew Keegan',
 'Andrew Lincoln',
 'Andrew Miller',
 'Andrew Neil',
 'Andrew Newberg',
 'Andrew Parks',
 'Andrew Robinson',
 'Andrew Sensenig',
 'Andrew Shim',
 'André Benjamin',
 'André Dussollier',
 'André Ramiro',
 'André Wilms',
 'Andy Anderson',
 'Andy Cohn',
 'Andy Davoli',
 'Andy Dick',
 'Andy García',
 'Andy Griffith',
 'Andy Kaufman',
 'Andy Lau',
 'Andy Nyman',
 'Andy Richter',
 'Andy Samberg',
 'Andy Serkis',
 'Aneurin Barnard',
 'Angela Bassett',
 'Angela Bettis',
 'Angelica Lee',
 'Angeliki Papoulia',
 'Angelina Idnani',
 'Angelina Jolie',
 'Angelo Josue Lozano Corzo',
 'Angie Dickinson',
 'Angie Harmon',
 'Angus Macfadyen',
 'Angus Scrimm',
 'Angélica Aragón',
 'Anika Noni Rose',
 'Anil Kapoor',
 'Anil Raman',
 'Anita Briem',
 'Anita Laurenzi',
 'Anita Mui',
 'Anita Page',
 'Anita Pallenberg',
 'Anjelica Huston',
 'Ann Altieri',
 'Ann Dowd',
 'Ann Lynn',
 'Ann Magnuson',
 'Ann Miller',
 'Anna Bolshova',
 'Anna Chlumsky',
 'Anna Claire Sneed',
 'Anna Faris',
 'Anna Friel',
 'Anna Gurji',
 'Anna Hutchison',
 'Anna Karina',
 'Anna Kendrick',
 'Anna Loos',
 'Anna Maria Horsford',
 'Anna Paquin',
 'Anna Popplewell',
 'Anna-Katharina Schwabroh',
 'AnnaSophia Robb',
 'Annabella Sciorra',
 'Annabelle Wallis',
 'Annabeth Gish',
 'Annalee Jefferies',
 'Anne Archer',
 'Anne Bancroft',
 'Anne Hathaway',
 'Anne Heche',
 'Anne Suzuki',
 'Anne-Marie Duff',
 'Anne-Marie Loop',
 'Annette Bening',
 'Annie Corley',
 'Ansel Elgort',
 'Anson Mount',
 'Anthony Anderson',
 'Anthony DeSando',
 'Anthony Edwards',
 'Anthony Heald',
 'Anthony Hopkins',
 'Anthony Johnson',
 'Anthony LaPaglia',
 'Anthony Mackie',
 'Anthony Perkins',
 'Anthony Quayle',
 'Anthony Quinn',
 'Anthony Rapp',
 'Anthony Stewart Head',
 'Anthony Wong',
 'Antoine McLean',
 'Anton Yelchin',
 'Antonio Banderas',
 'Antonio Cantafora',
 'Anushka Sharma',
 'Anwar Congo',
 'Anya Taylor-Joy',
 'Archie Kao',
 'Ari Folman',
 'Ari Graynor',
 'Ariadna Gil',
 'Ariana Richards',
 'Ariana Stephens',
 'Ariel Levy',
 'Ariel Winter',
 'Arielle Kebbel',
 'Arif Herati',
 'Arié Elmaleh',
 'Arletty',
 'Arly Jover',
 'Armand Assante',
 'Armando Espitia',
 'Armie Hammer',
 'Armin Habibovich',
 'Armin Mueller-Stahl',
 'Armin Rohde',
 'Arnold Schwarzenegger',
 'Arshad Warsi',
 'Arsinée Khanjian',
 'Art Carney',
 'Art Hsu',
 'Artem Mishin',
 'Arthur Agee',
 'Arthur Dupont',
 'Arthur Hill',
 'Arthur Kennedy',
 'Artie Ahr',
 'Artie Lange',
 'Artyom Bogucharsky',
 'Asa Butterfield',
 'Ashanti',
 'Ashleigh Gryzko',
 'Ashley Bell',
 'Ashley Greene',
 'Ashley Hayes',
 'Ashley Johnson',
 'Ashley Judd',
 'Ashley Laurence',
 'Ashley Olsen',
 'Ashley Scott',
 'Ashley Tisdale',
 'Ashton Kutcher',
 'Asia Argento',
 'Asin Thottumkal',
 'Astrid Bergès-Frisbey',
 'Astro',
 'Atossa Leoni',
 'Aubrey Plaza',
 'Audrey Hepburn',
 'Audrey Tautou',
 'Austin Basis',
 'Austin Butler',
 'Austin Stoker',
 'Ava Gardner',
 'Avery Schreiber',
 'Avraham Shalom',
 'Ayelet Zurer',
 'Ayesha Omar',
 'Ayush Tandon',
 'Aziz Ansari',
 'Aziz Muradillayev',
 'BD Wong',
 'Baby Bash',
 'Bae Doona',
 'Bahare Seddiqi',
 'Bai Ling',
 'Bailee Madison',
 'Balthazar Getty',
 'Bam Margera',
 'Barack Obama',
 'Barbara Adams',
 'Barbara Bach',
 'Barbara Boxer',
 'Barbara Brenner',
 'Barbara Carrera',
 'Barbara Ehrenreich',
 'Barbara Harris',
 'Barbara Hershey',
 'Barbara Mamabolo',
 'Barbra Streisand',
 'Barney Clark',
 'Barret Oliver',
 'Barry Bostwick',
 'Barry Corbin',
 'Barry Foster',
 'Barry McEvoy',
 'Barry Miller',
 'Barry Pepper',
 'Barry Watson',
 'Bart Robinson Cook',
 'Bashar Rahal',
 'Basil Rathbone',
 'Beatrice Straight',
 'Beau Bridges',
 'Beau Knapp',
 'Bebe Daniels',
 'Bebe Neuwirth',
 'Bee Vang',
 'Bel Powley',
 'Belinda Becker',
 'Bella Heathcote',
 'Bella Thorne',
 'Belladonna',
 'Belén Rueda',
 'Ben Affleck',
 'Ben Barnes',
 'Ben Browder',
 'Ben Burtt',
 'Ben Chaplin',
 'Ben Cross',
 'Ben Davies',
 'Ben Diskin',
 'Ben Drew',
 'Ben Feldman',
 'Ben Foster',
 'Ben Garant',
 'Ben Gazzara',
 'Ben Kingsley',
 'Ben Lyon',
 'Ben Mendelsohn',
 'Ben Miller',
 'Ben Piazza',
 'Ben Rovner',
 'Ben Schwartz',
 'Ben Shenkman',
 'Ben Stiller',
 'Ben Weber',
 'Ben Whishaw',
 'Ben Youcef',
 'Benedict Cumberbatch',
 'Benicio del Toro',
 'Benjamin Bratt',
 'Benjamin Dickinson',
 'Benjamin Walker',
 'Benno Fürmann',
 'Benoît Magimel',
 'Benoît Poelvoorde',
 'Bentley Mitchum',
 'Bernadette Peters',
 'Bernard Noël',
 'Bernie Mac',
 'Bess Armstrong',
 'Bessie Love',
 'Beth Broderick',
 'Beth Grant',
 'Betsy Russell',
 'Bette Davis',
 'Bette Midler',
 'Betty Hutton',
 'Betty Schuurman',
 'Betty Thomas',
 'Betty White',
 "Beverly D'Angelo",
 'Beyoncé Knowles',
 'Bhole Baba',
 'Bhumika Chawla',
 'Bianca Bree',
 'Big Boi',
 'Bijou Phillips',
 'Bill Baird',
 'Bill Barretta',
 'Bill Bellamy',
 'Bill Billions',
 'Bill Camp',
 'Bill Clinton',
 'Bill Fagerbakke',
 'Bill Goldberg',
 'Bill Hader',
 'Bill Lobley',
 'Bill Maher',
 'Bill Melendez',
 'Bill Moseley',
 'Bill Murray',
 'Bill Nighy',
 'Bill Paxton',
 'Bill Pullman',
 'Bill Walton',
 'Billy Bob Thornton',
 'Billy Boyd',
 'Billy Burke',
 'Billy Campbell',
 'Billy Connolly',
 'Billy Crudup',
 'Billy Crystal',
 'Billy Dee Williams',
 'Billy Hufsey',
 'Billy Ray Cyrus',
 'Billy West',
 'Billy Zane',
 'Bipasha Basu',
 'Birgitte Federspiel',
 'Birgitte Hjort Sørensen',
 'Birol Ünel',
 'Björk',
 'Blair Underwood',
 'Blake Clark',
 'Blake Heron',
 'Blake Lively',
 'Blanchard Ryan',
 'Blayne Weaver',
 'Blondin Miguel',
 'Blythe Auffarth',
 'Blythe Danner',
 'Bob Balaban',
 'Bob Costas',
 'Bob Dylan',
 'Bob Gunton',
 'Bob Hoskins',
 'Bob Odenkirk',
 'Bob Papenbrook',
 'Bob Zmuda',
 'Bobby Campo',
 'Bobby Cannavale',
 'Bobby Coleman',
 'Bobby Kendall',
 'Bojana Novaković',
 'Bokeem Woodbine',
 'Bolo Yeung',
 'Bong Soo Han',
 'Bongkoj Khongmalai',
 'Bonnie Bartlett',
 'Bonnie Bedelia',
 'Bonnie Henna',
 'Bonnie Hunt',
 'Bono',
 'Bonz Malone',
 'Boris Kodjoe',
 'Boyd Banks',
 'Brad Carter',
 'Brad Dourif',
 'Brad Hunt',
 'Brad Johnson',
 'Brad Loree',
 'Brad Pitt',
 'Brad Renfro',
 'Bradford Dillman',
 'Bradley Cooper',
 'Brady Corbet',
 'Brandon Bales',
 'Brandon Gonzales',
 'Brandon Henschel',
 'Brandon Lee',
 'Brandon Ratcliff',
 'Brandon Routh',
 'Brandon T. Jackson',
 'Brandt Wille',
 'Brandy Maasch',
 'Brandy Whitford',
 'Branko Đurić',
 'Breckin Meyer',
 'Bree Williamson',
 'Brenda Blethyn',
 'Brenda Strong',
 'Brenda Vaccaro',
 'Brendan "Doogie" Milewski',
 'Brendan Cowell',
 'Brendan Fehr',
 'Brendan Fletcher',
 'Brendan Fraser',
 'Brendan Gleeson',
 'Brendan Mackey',
 'Brendan Sexton III',
 'Brent Spiner',
 'Brenton Thwaites',
 'Brett Granstaff',
 'Brett Kelly',
 'Brian Austin Green',
 'Brian Blessed',
 'Brian Boland',
 'Brian Bosworth',
 'Brian Cox',
 'Brian Dennehy',
 'Brian Geraghty',
 'Brian Herzlinger',
 'Brian Hooks',
 'Brian Keith Allen',
 'Brian Krause',
 'Brian Murray',
 "Brian O'Halloran",
 'Brian Van Holt',
 'Briana Evigan',
 'Brianne Siddall',
 'Bridget Fonda',
 'Bridget Moynahan',
 'Bridgette Wilson',
 'Brie Gabrielle',
 'Brie Larson',
 'Brighton Sharbino',
 'Brigitte Bardot',
 'Brigitte Helm',
 'Brigitte Nielsen',
 'Brit Marling',
 'Brit Morgan',
 'Britney Spears',
 'Britt Ekland',
 'Britt Robertson',
 'Brittany Curran',
 'Brittany Daniel',
 'Brittany Murphy',
 'Brittany Snow',
 'Brittney Powell',
 'Brock Peters',
 'Brooke Adams',
 'Brooke Coleman',
 "Brooke D'Orsay",
 'Brooke Langton',
 'Brooke Shields',
 'Bruce Altman',
 'Bruce Campbell',
 'Bruce Davison',
 'Bruce Dern',
 'Bruce Greenwood',
 'Bruce Jones',
 'Bruce McGill',
 'Bruce Payne',
 'Bruce Spence',
 'Bruce Willis',
 'Bruno Campos',
 'Bruno Cremer',
 'Bruno Ganz',
 'Bryan Callen',
 'Bryan Cranston',
 'Bryan Greenberg',
 'Bryce Dallas Howard',
 "Brían F. O'Byrne",
 'Bud Cort',
 'Bud Luckey',
 'Burghart Klaußner',
 'Burl Ives',
 'Burt Lancaster',
 'Burt Reynolds',
 'Burt Ward',
 'Burt Young',
 'Busta Rhymes',
 'Buster Keaton',
 'Buzz Aldrin',
 'Byron Mann',
 'Bálint Péntek',
 'Bárbara Goenaga',
 'Bárbara Mori',
 'Béatrice Bonifassi',
 'Béatrice Dalle',
 'Béla Dóra',
 'Bérénice Bejo',
 'C. Fraser Press',
 'C. Thomas Howell',
 'CJ Adams',
 'Caerthan Banks',
 'Caio Junqueira',
 'Caitlin Clarke',
 'Caitlin Fitzgerald',
 'Caitlin Keats',
 'Caleb Landry Jones',
 'Callan McAuliffe',
 'Callum Blue',
 'Callum Keith Rennie',
 'Calvin Levels',
 'Calvin Lockhart',
 'Cam Clarke',
 'Cam Gigandet',
 'Cameron Bright',
 'Cameron Diaz',
 'Cameron Mills',
 'Cameron Richardson',
 'Camila Márdila',
 'Camilla Belle',
 'Campbell Scott',
 'Candace Evanofski',
 'Candace Hutson',
 'Candela Fernández',
 'Candice Bergen',
 'Candice Coke',
 'Candise Lakota',
 'Candy Ford',
 'Cara Delevingne',
 'Carey Lowell',
 'Carey Means',
 'Carey Mulligan',
 'Carice van Houten',
 'Carl Weathers',
 'Carla Gugino',
 'Carlo Cecchi',
 'Carlo Verdone',
 'Carlos Alberto',
 'Carlos Belloso',
 'Carlos Gallardo',
 'Carlos Mencia',
 'Carlos Montalbán',
 'Carlos Pratts',
 'Carly Schroeder',
 'Carmen Ejogo',
 'Carmen Electra',
 'Carmen Maura',
 'Carol Block',
 'Carol Burnett',
 'Carol Kane',
 'Carole Bouquet',
 'Carole Davis',
 'Caroline Aaron',
 'Caroline Barry',
 "Caroline D'Amore",
 'Caroline Dhavernas',
 'Caroline Goodall',
 'Caroline Kava',
 'Caroline Williams',
 'Carolyn Saxon',
 'Carrie Coon',
 'Carrie Fisher',
 'Carrie MacLemore',
 'Carrie Snodgress',
 'Carrie-Anne Moss',
 'Carroll Baker',
 "Carroll O'Connor",
 'Carter Jenkins',
 'Cary Elwes',
 'Cary Grant',
 'Cary-Hiroyuki Tagawa',
 'Cas Anvar',
 'Casey Affleck',
 'Casey Dubois',
 'Casey Gooden',
 'Casper Christensen',
 'Casper Van Dien',
 'Cassandra Scerbo',
 'Cassidy Gifford',
 'Catalina Sandino Moreno',
 'Cate Blanchett',
 'Catharine Bolz',
 'Catherine Deneuve',
 'Catherine Florent',
 'Catherine Hicks',
 'Catherine Keener',
 'Catherine Lloyd Burns',
 'Catherine McCormack',
 "Catherine O'Hara",
 'Catherine Oxenberg',
 'Catherine Zeta-Jones',
 'Cathy Moriarty',
 'Catriona MacColl',
 'Cayden Boyd',
 'Cecil Kellaway',
 'Cecilia Cheung',
 'Cecilia Narova',
 'Cedric Hardwicke',
 'Cedric the Entertainer',
 'Cee Lo Green',
 'Celia Imrie',
 'Cesar Garcia',
 'Cesar Ramos',
 'Chace Crawford',
 'Chad Allen',
 'Chad Lindberg',
 'Chad Michael Murray',
 'Chadwick Boseman',
 'Chaim Girafi',
 'Chaim Topol',
 'Chalo González',
 'Chandler Canterbury',
 'Chandra West',
 'Chaney Kley',
 'Chang Chen',
 'Channing Tatum',
 'Charis Michelsen',
 'Charles Aznavour',
 'Charles Berling',
 'Charles Dance',
 'Charles Durning',
 'Charles Gray',
 'Charles Grodin',
 'Charles Henry Wyson',
 'Charles King',
 'Charles Ludlam',
 'Charles Martin Smith',
 'Charles Napier',
 'Charles S. Dutton',
 'Charlie Chaplin',
 'Charlie Cox',
 'Charlie Day',
 'Charlie Hunnam',
 'Charlie Korsmo',
 'Charlie McDermott',
 'Charlie Rowe',
 'Charlie Sheen',
 'Charlie Tahan',
 'Charlie Watts',
 'Charlie Yeung',
 'Charlize Theron',
 'Charlotte Bøving',
 'Charlotte Frogner',
 'Charlotte Gainsbourg',
 'Charlotte Le Bon',
 'Charlotte Lewis',
 'Charlotte Rampling',
 'Charlotte Riley',
 'Charlotte Stewart',
 'Charlton Heston',
 'Chase Masterson',
 'Chatchai Plengpanich',
 'Chazz Palminteri',
 'Cheech Marin',
 'Chehon Wespi-Tschopp',
 'Chelcie Ross',
 'Chelse Swain',
 'Chelsea Field',
 'Chelsea Handler',
 'Chelsea Rendon',
 'Chen Dao-Ming',
 'Chen Sicheng',
 'Chengwu Guo',
 'Chenoa Maxwell',
 'Cher',
 'Cherami Leigh',
 'Cheryl Campbell',
 'Cheryl Hines',
 'Cheryl Ladd',
 'Cheryl Tiegs',
 'Chevy Chase',
 'Cheyenne Jackson',
 'Chi Cao',
 'Chi McBride',
 'Chiara Mastroianni',
 'Chip Bent',
 'Chiwetel Ejiofor',
 'Chloe Hollings',
 'Chloë Grace Moretz',
 'Chloë Sevigny',
 'Choi Min-sik',
 'Chow Yun-fat',
 'Chris Bisson',
 'Chris Brown',
 'Chris Carey',
 'Chris Carlson',
 'Chris Carmack',
 'Chris Chatman',
 'Chris Cooper',
 'Chris Diamantopoulos',
 'Chris Doran',
 'Chris Eigeman',
 'Chris Elliott',
 'Chris Evans',
 'Chris Hemsworth',
 'Chris Ivan Cevic',
 'Chris Kattan',
 'Chris Kelly',
 'Chris Klein',
 'Chris Massoglia',
 'Chris Messina',
 'Chris Miller',
 'Chris New',
 'Chris Noth',
 "Chris O'Donnell",
 'Chris Penn',
 'Chris Phillips',
 'Chris Pine',
 'Chris Pontius',
 'Chris Pratt',
 'Chris Riggi',
 'Chris Rock',
 'Chris Sanders',
 'Chris Sarandon',
 'Chris Tucker',
 'Chris Warren, Jr.',
 'Chris Wedge',
 'Chris Weitz',
 'Chris Young',
 'Christa Brittany  Allen',
 'Christen Mooney',
 'Christian Bale',
 'Christian Byers',
 'Christian Campbell',
 'Christian Clavier',
 'Christian Kane',
 'Christian Kapper',
 'Christian McKay',
 'Christian Rudder',
 'Christian Slater',
 'Christian Vazquez',
 'Christina Aguilera',
 'Christina Applegate',
 'Christina Brucato',
 'Christina Chambers',
 'Christina Hart',
 'Christina Milian',
 'Christina Ricci',
 'Christine Cavanaugh',
 'Christine Dunford',
 'Christine Taylor',
 'Christoph Maria Herbst',
 'Christoph Waltz',
 'Christophe Cherki',
 'Christopher Abbott',
 'Christopher Atkins',
 'Christopher Beiring',
 'Christopher Carley',
 'Christopher Curry',
 'Christopher Denham',
 'Christopher Eccleston',
 'Christopher Egan',
 'Christopher George',
 'Christopher Gorham',
 'Christopher Guest',
 'Christopher Judge',
 'Christopher Knights',
 'Christopher Lambert',
 'Christopher Lee',
 'Christopher Lloyd',
 'Christopher Martin',
 'Christopher McDonald',
 'Christopher Meloni',
 'Christopher Meyer',
 'Christopher Mintz-Plasse',
 'Christopher Plummer',
 'Christopher Reeve',
 'Christopher Reid',
 'Christopher Robin Miller',
 'Christopher Scott Cherot',
 'Christopher Shand',
 'Christopher Simpson',
 'Christopher Stone',
 'Christopher Toler',
 'Christopher Walken',
 'Chrystee Pharris',
 'Chuck Campbell',
 'Chuck Norris',
 ...]

In [80]:
movies[movies['title']=='The Death and Life of Bobby Z']

,movie_id,title,overview,genres,keywords,cast,Director,vote_count,vote_average,cast1,cast2,cast3,tags
3302,10425,The Death and Life of Bobby Z,"[A, DEA, agent, provides, former, Marine, Tim,...","[Drama, Action, Thriller, Crime]","[vineyard, rifle, drugtrade, violence, shotint...","[PaulWalker, LaurenceFishburne, OliviaWilde]",[JohnHerzfeld],103,5.8,Paul Walker,Laurence Fishburne,Olivia Wilde,"[A, DEA, agent, provides, former, Marine, Tim,..."

In [81]:
movies[movies['cast1']=='Paul Walker']

,movie_id,title,overview,genres,keywords,cast,Director,vote_count,vote_average,cast1,cast2,cast3,tags
99,9799,The Fast and the Furious,"[Domenic, Toretto, is, a, Los, Angeles, street...","[Action, Crime, Thriller]","[streetgang, carrace, undercover, auto-tuning,...","[PaulWalker, VinDiesel, MichelleRodriguez]",[RobCohen],3428,6.6,Paul Walker,Vin Diesel,Michelle Rodriguez,"[Domenic, Toretto, is, a, Los, Angeles, street..."
483,9562,Timeline,"[A, group, of, archaeological, students, becom...","[Action, Adventure, ScienceFiction]","[professor, timetravel, quantummechanics, hund...","[PaulWalker, FrancesO'Connor, GerardButler]",[RichardDonner],318,5.4,Paul Walker,Frances O'Connor,Gerard Butler,"[A, group, of, archaeological, students, becom..."
500,584,2 Fast 2 Furious,"[It's, a, major, double-cross, when, former, p...","[Action, Crime, Thriller]","[miami, carrace, sportscar, losangeles, car, a...","[PaulWalker, TyreseGibson, EvaMendes]",[JohnSingleton],2028,6.2,Paul Walker,Tyrese Gibson,Eva Mendes,"[It's, a, major, double-cross, when, former, p..."
987,11968,Into the Blue,"[When, they, take, some, friends, on, an, extr...","[Action, Thriller, Adventure, Crime]","[diving, cocaine, shipwreck, sailing, airplane...","[PaulWalker, JessicaAlba, ScottCaan]",[JohnStockwell],458,5.8,Paul Walker,Jessica Alba,Scott Caan,"[When, they, take, some, friends, on, an, extr..."
1175,9036,Eight Below,"[In, the, Antarctic,, after, an, expedition, w...","[Adventure, Drama, Family]","[expedition, pilot, survival, sleddogs, seal]","[PaulWalker, BruceGreenwood, MoonBloodgood]",[FrankMarshall],542,6.7,Paul Walker,Bruce Greenwood,Moon Bloodgood,"[In, the, Antarctic,, after, an, expedition, w..."
1748,254473,Brick Mansions,"[In, a, dystopian, Detroit,, grand, houses, th...","[Action, Crime, Drama]","[martialarts, atomicbomb, ghetto, parkour, cop...","[PaulWalker, DavidBelle, RZA]",[CamilleDelamarre],615,5.7,Paul Walker,David Belle,RZA,"[In, a, dystopian, Detroit,, grand, houses, th..."
1989,40688,Meet the Deedles,"[Two, surfers, end, up, as, Yellowstone, park,...","[Animation, Comedy, Family]",[],"[PaulWalker, JohnAshton, DennisHopper]",[SteveBoyum],19,4.1,Paul Walker,John Ashton,Dennis Hopper,"[Two, surfers, end, up, as, Yellowstone, park,..."
2441,7304,Running Scared,"[After, a, drug-op, gone, bad,, Joey, Gazelle,...","[Action, Crime, Drama, Thriller]","[icehockey, racism, pedophile, throatslitting,...","[PaulWalker, CameronBright, VeraFarmiga]",[WayneKramer],331,7.0,Paul Walker,Cameron Bright,Vera Farmiga,"[After, a, drug-op, gone, bad,, Joey, Gazelle,..."
3302,10425,The Death and Life of Bobby Z,"[A, DEA, agent, provides, former, Marine, Tim,...","[Drama, Action, Thriller, Crime]","[vineyard, rifle, drugtrade, violence, shotint...","[PaulWalker, LaurenceFishburne, OliviaWilde]",[JohnHerzfeld],103,5.8,Paul Walker,Laurence Fishburne,Olivia Wilde,"[A, DEA, agent, provides, former, Marine, Tim,..."

In [82]:
def get_movies_by_actor(movies,actor_name):
    # create boolean masks to filter movies that the actor appears in each of the three cast columns
    mask1 = movies['cast1'].apply(lambda x: pd.notna(x) and actor_name in x)
    mask2 = movies['cast2'].apply(lambda x: pd.notna(x) and actor_name in x)
    mask3 = movies['cast3'].apply(lambda x: pd.notna(x) and actor_name in x)

    # combine the three masks using logical OR to get a single mask for all movies featuring the actor
    mask = mask1 | mask2 | mask3

    # subset the movies dataframe to include only the desired columns
    subset = movies.loc[mask, ['title', 'genres', 'cast', 'Director']]

    return subset

In [83]:
get_movies_by_actor(movies,'Paul Walker')

,title,genres,cast,Director
44,Furious 7,[Action],"[VinDiesel, PaulWalker, DwayneJohnson]",[JamesWan]
99,The Fast and the Furious,"[Action, Crime, Thriller]","[PaulWalker, VinDiesel, MichelleRodriguez]",[RobCohen]
204,Fast Five,"[Action, Thriller, Crime]","[VinDiesel, PaulWalker, JordanaBrewster]",[JustinLin]
483,Timeline,"[Action, Adventure, ScienceFiction]","[PaulWalker, FrancesO'Connor, GerardButler]",[RichardDonner]
500,2 Fast 2 Furious,"[Action, Crime, Thriller]","[PaulWalker, TyreseGibson, EvaMendes]",[JohnSingleton]
987,Into the Blue,"[Action, Thriller, Adventure, Crime]","[PaulWalker, JessicaAlba, ScottCaan]",[JohnStockwell]
1175,Eight Below,"[Adventure, Drama, Family]","[PaulWalker, BruceGreenwood, MoonBloodgood]",[FrankMarshall]
1748,Brick Mansions,"[Action, Crime, Drama]","[PaulWalker, DavidBelle, RZA]",[CamilleDelamarre]
1989,Meet the Deedles,"[Animation, Comedy, Family]","[PaulWalker, JohnAshton, DennisHopper]",[SteveBoyum]
2004,Joy Ride,"[Mystery, Thriller, Drama]","[SteveZahn, PaulWalker, LeeleeSobieski]",[JohnDahl]
2441,Running Scared,"[Action, Crime, Drama, Thriller]","[PaulWalker, CameronBright, VeraFarmiga]",[WayneKramer]
2552,The Skulls,"[Crime, Drama, Thriller]","[JoshuaJackson, PaulWalker, HillHarper]",[RobCohen]
3302,The Death and Life of Bobby Z,"[Drama, Action, Thriller, Crime]","[PaulWalker, LaurenceFishburne, OliviaWilde]",[JohnHerzfeld]

* Recommendation on Actors -:

In [84]:
def recommended_movies_by_actor(actor_name, movies, similarity):
     
    # create boolean masks to filter movies that the actor appears in each of the three cast columns
    if 
    mask1 = movies['cast1'].apply(lambda x: pd.notna(x) and actor_name in x)
    mask2 = movies['cast2'].apply(lambda x: pd.notna(x) and actor_name in x)
    mask3 = movies['cast3'].apply(lambda x: pd.notna(x) and actor_name in x)

    # combine the three masks using logical OR to get a single mask for all movies featuring the actor
    mask = mask1 | mask2 | mask3

    # subset the movies dataframe to include only the desired columns
    subset = movies.loc[mask, ['title', 'genres', 'cast', 'Director']
    # Check if any movies are available for the specified actor
                        
    if not movies[['cast1', 'cast2', 'cast3']].apply(lambda x: actor_name in x.values).any().any():
        return "No movies found for actor " + actor_name
    
    # Get the index of the first movie that the actor appears in
    movie_index = movies[['cast1', 'cast2', 'cast3']].apply(lambda x: actor_name in x.values).idxmax()
    
    # Compute the distances between this movie and all other movies
    distances = similarity[movie_index]
    
    # Sort the distances in descending order and get the top 10 movies
    movie_indices = sorted(range(len(distances)), key=lambda i: distances[i], reverse=True)[1:11]
    recommended_movies = movies.iloc[movie_indices][['title', 'genres', 'cast', 'Director']]
    
    return recommended_movies

SyntaxError: invalid syntax (1101872187.py, line 4)

In [ ]:
recommended_Actor_movies('Paul Walker', movies, similarity)

# Recommendation By Director :

* Directors Movies -:

In [85]:
mov.head(1)

,movie_id,title,overview,genres,keywords,cast,crew,vote_count,vote_average,cast1,cast2,cast3
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],11800,7.2,Sam Worthington,Zoe Saldana,Sigourney Weaver

In [86]:
mov=mov.rename(columns={'crew': 'Director'})

In [87]:
mov.head(1)

,movie_id,title,overview,genres,keywords,cast,Director,vote_count,vote_average,cast1,cast2,cast3
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],11800,7.2,Sam Worthington,Zoe Saldana,Sigourney Weaver

In [88]:
# Extract the 'Director' column as a list of lists
directors = mov['Director'].tolist()

# Flatten the list of lists into a single list and convert to set to remove duplicates
unique_directors = set(director for sublist in directors for director in sublist)

# Sort the set of unique directors in alphabetical order and convert back to list
sorted_directors = sorted(unique_directors)

In [89]:
sorted_directors

['Aaron Hann',
 'Aaron Schneider',
 'Abel Ferrara',
 'Adam Brooks',
 'Adam Carolla',
 'Adam Goldberg',
 'Adam Green',
 'Adam Jay Epstein',
 'Adam Marcus',
 'Adam McKay',
 'Adam Rapp',
 'Adam Rifkin',
 'Adam Shankman',
 'Adrian Lyne',
 'Adrienne Shelly',
 'Agnieszka Holland',
 'Agnieszka Wojtowicz-Vosloo',
 'Agustín Díaz Yanes',
 'Aki Kaurismäki',
 'Akira Kurosawa',
 'Akiva Goldsman',
 'Akiva Schaffer',
 'Al Silliman Jr.',
 'Alain Resnais',
 'Alan Alda',
 'Alan Cohn',
 'Alan J. Pakula',
 'Alan Metter',
 'Alan Parker',
 'Alan Poul',
 'Alan Rudolph',
 'Alan Shapiro',
 'Alan Smithee',
 'Alan Taylor',
 'Alan Yuen',
 'Albert Brooks',
 'Albert Hughes',
 'Alejandro Agresti',
 'Alejandro Amenábar',
 'Alejandro González Iñárritu',
 'Alejandro Monteverde',
 'Aleksandr Veledinskiy',
 'Aleksey German',
 'Alex Cox',
 'Alex Craig Mann',
 'Alex Garland',
 'Alex Gibney',
 'Alex Kendrick',
 'Alex Proyas',
 'Alex Ranarivelo',
 'Alex Rivera',
 'Alex Smith',
 'Alex Zamm',
 'Alex van Warmerdam',
 'Alexander Payne',
 'Alexander Witt',
 'Alexandre Aja',
 'Alfonso Cuarón',
 'Alfred Hitchcock',
 'Alice Wu',
 'Alison Maclean',
 'Alister Grierson',
 'Allan Arkush',
 'Allan Dwan',
 'Allen Coulter',
 'Allen Hughes',
 'Allison Anders',
 'Allison Burnett',
 'Amanda Gusack',
 'Amat Escalante',
 'Amy Heckerling',
 'Amy Holden Jones',
 'Analeine Cal y Mayor',
 'Anand Tucker',
 'Andrea Arnold',
 'Andrea Di Stefano',
 'Andrei Konchalovsky',
 'Andrei Tarkovsky',
 'Andrew Adamson',
 'Andrew Bergman',
 'Andrew Bujalski',
 'Andrew Currie',
 'Andrew Davis',
 'Andrew Dominik',
 'Andrew Douglas',
 'Andrew Erwin',
 'Andrew Fleming',
 'Andrew Haigh',
 'Andrew Hyatt',
 'Andrew Jarecki',
 'Andrew Leman',
 'Andrew Morahan',
 'Andrew Niccol',
 'Andrew Stanton',
 'Andrew Steggall',
 'Andrew Traucki',
 'Andrey Zvyagintsev',
 'Andrucha Waddington',
 'Andrzej Bartkowiak',
 'André Téchiné',
 'André Øvredal',
 'Andrés Couturier',
 'Andy Cadiff',
 'Andy Fickman',
 'Andy García',
 'Andy Muschietti',
 'Andy Tennant',
 'Ang Lee',
 'Angela Robinson',
 'Angelina Jolie',
 'Angelo Pizzo',
 'Anna Mastro',
 'Anna Muylaert',
 'Annabel Jankel',
 'Anne Fletcher',
 'Anne Fontaine',
 'Anthony C. Ferrante',
 'Anthony Hemingway',
 'Anthony Hickox',
 'Anthony Mann',
 'Anthony Minghella',
 "Anthony O'Brien",
 'Anthony Powell',
 'Anthony Russo',
 'Anthony Silverston',
 'Anthony Stacchi',
 'Antoine Fuqua',
 'Anton Corbijn',
 'Antonia Bird',
 'Antonio Banderas',
 'Antonio Simoncini',
 'Antony Hoffman',
 'Anurag Basu',
 'Ari Folman',
 'Ari Sandel',
 'Arie Posin',
 'Ariel Vromen',
 'Arjun Sablok',
 'Asger Leth',
 'Asghar Farhadi',
 'Ash Baron-Cohen',
 'Ash Brannon',
 'Ashish R. Mohan',
 'Atom Egoyan',
 'Audrey Wells',
 'Ava DuVernay',
 'Avi Nesher',
 'Ayan Mukherjee',
 'Babak Najafi',
 'Babar Ahmed',
 'Baltasar Kormákur',
 'Barbet Schroeder',
 'Barbra Streisand',
 'Barnaby Thompson',
 'Barrett Esposito',
 'Barry Cook',
 'Barry Levinson',
 'Barry Skolnick',
 'Barry Sonnenfeld',
 'Barry W. Blaustein',
 'Bart Freundlich',
 'Baz Luhrmann',
 'Becky Smith',
 'Beeban Kidron',
 'Ben Affleck',
 'Ben Falcone',
 'Ben Garant',
 'Ben Gluck',
 'Ben Lewin',
 'Ben Sharpsteen',
 'Ben Stassen',
 'Ben Stiller',
 'Ben Wheatley',
 'Ben Younger',
 'Benedek Fliegauf',
 'Benedikt Erlingsson',
 'Benh Zeitlin',
 'Benjamin Dickinson',
 'Bennett Miller',
 'Benni Diez',
 'Benny Boom',
 'Benson Lee',
 'Bernardo Bertolucci',
 'Bernhard Wicki',
 'Beto Gómez',
 'Betty Thomas',
 'Bibo Bergeron',
 'Bigas Luna',
 'Bill Benenson',
 'Bill Condon',
 'Bill Duke',
 'Bill Melendez',
 'Bill Muir',
 'Bill Paxton',
 'Bill Plympton',
 'Bille August',
 'Bille Woodruff',
 'Billy Bob Thornton',
 'Billy Kent',
 'Billy Ray',
 'Billy Wilder',
 'Blair Erickson',
 'Blair Hayes',
 'Blake Edwards',
 'Blaž Završnik',
 'Bo Welch',
 'Bo Zenga',
 'Boaz Yakin',
 'Bob Clark',
 'Bob Dolman',
 'Bob Fosse',
 'Bob Giraldi',
 'Bob Gosse',
 'Bob Odenkirk',
 'Bob Rafelson',
 'Bob Saget',
 'Bob Spiers',
 'Bobby Farrelly',
 'Bobby Roth',
 'Bobcat Goldthwait',
 'Bong Joon-ho',
 'Bonnie Hunt',
 'Boris Rodriguez',
 'Brad Anderson',
 'Brad Bird',
 'Brad Copeland',
 'Brad Furman',
 'Brad J. Silverman',
 'Brad Peyton',
 'Brad Silberling',
 'Bradley Parker',
 'Bradley Rust Gray',
 'Brandon Camp',
 'Brandon Cronenberg',
 'Brandon Trost',
 'Breck Eisner',
 'Brenda Chapman',
 'Brendan Malloy',
 'Brett Leonard',
 'Brett Piper',
 'Brett Ratner',
 'Brian A Miller',
 'Brian Baugh',
 'Brian Caunter',
 'Brian Dannelly',
 'Brian De Palma',
 'Brian Gibson',
 'Brian Helgeland',
 'Brian Henson',
 'Brian Herzlinger',
 'Brian Klugman',
 'Brian Koppelman',
 'Brian Levant',
 'Brian Percival',
 'Brian Robbins',
 'Brian Taylor',
 'Brian Trenchard-Smith',
 'Brian Yuzna',
 'Britt Allcroft',
 'Bronwen Hughes',
 'Bruce Beresford',
 'Bruce Campbell',
 'Bruce Hunt',
 'Bruce MacDonald',
 'Bruce Malmuth',
 'Bruce McCulloch',
 'Bruce McDonald',
 'Bruce Paltrow',
 'Bruno Barreto',
 'Bryan Barber',
 'Bryan Singer',
 'Burr Steers',
 'Byron Howard',
 'C. Jay Cox',
 'Callan Brunker',
 'Callie Khouri',
 'Cameron Crowe',
 'Camille Delamarre',
 'Carl Franklin',
 'Carl Rinsch',
 'Carl Theodor Dreyer',
 'Carlos Carrera',
 'Carlos Saldanha',
 'Carlos Saura',
 'Carmen Marron',
 'Carol Reed',
 'Caroline Link',
 'Carroll Ballard',
 'Carter Smith',
 'Cary Bell',
 'Caryn Waechter',
 'Cassandra Nicolaou',
 'Catherine Gund',
 'Catherine Hardwicke',
 'Catherine Jelski',
 'Cathy Malkasian',
 'Cecil B. DeMille',
 'Cedric Nicolas-Troyan',
 'Chad Hartigan',
 'Chad Kapper',
 'Charles Adelman',
 'Charles Binamé',
 'Charles Ferguson',
 'Charles Herman-Wurmfeld',
 'Charles Martin Smith',
 'Charles Matthau',
 'Charles Robert Carner',
 'Charles S. Dutton',
 'Charles Shyer',
 'Charles Stone III',
 'Charles T. Kanganis',
 'Charlie Chaplin',
 'Charlie Kaufman',
 'Charlie Levi',
 'Chatrichalerm Yukol',
 'Chen Kaige',
 'Cheryl Dunye',
 'Chris Atkins',
 'Chris Buck',
 'Chris Carter',
 'Chris Columbus',
 "Chris D'Arienzo",
 'Chris Eyre',
 'Chris Gorak',
 'Chris Kentis',
 'Chris Koch',
 'Chris Marker',
 'Chris Miller',
 'Chris Morris',
 'Chris Nahon',
 'Chris Noonan',
 'Chris Paine',
 'Chris Renaud',
 'Chris Rock',
 'Chris Sanders',
 'Chris Shadley',
 'Chris Stokes',
 'Chris Wedge',
 'Chris Weitz',
 'Chris Williams',
 'Christian Alvart',
 'Christian Carion',
 'Christian Ditter',
 'Christian Duguay',
 'Christian E. Christiansen',
 'Christian Robinson',
 'Christian Sesma',
 'Christian Volckman',
 'Christine Jeffs',
 'Christophe Ali',
 'Christophe Barratier',
 'Christophe Gans',
 'Christopher B. Landon',
 'Christopher Bessette',
 'Christopher Cain',
 'Christopher Erskin',
 'Christopher Guest',
 'Christopher Hutson',
 'Christopher Leitch',
 'Christopher McQuarrie',
 'Christopher Nolan',
 'Christopher Roberts',
 'Christopher Scott Cherot',
 'Christopher Smith',
 'Christopher Spencer',
 'Chuck Bowman',
 'Chuck Russell',
 'Chuck Sheetz',
 'Ciaran Foy',
 'Clare Kilner',
 'Clark Baker',
 'Clark Gregg',
 'Clark Johnson',
 'Claude Chabrol',
 'Claude Miller',
 'Claudia Llosa',
 'Claudia Sainte-Luce',
 'Clint Eastwood',
 'Clive Barker',
 'Cody Cameron',
 'Coky Giedroyc',
 'Colin Higgins',
 'Colin Minihan',
 'Colin Strause',
 'Colin Trevorrow',
 'Collin Joseph Neal',
 'Collin Schiffli',
 'Conor McMahon',
 'Conor McPherson',
 'Conrad Vernon',
 'Corbin Bernsen',
 'Corey Grant',
 'Corey Yuen Kwai',
 'Cory Edwards',
 'Costa-Gavras',
 'Courtney Hunt',
 'Courtney Solomon',
 'Craig Bolotin',
 'Craig Brewer',
 'Craig Gillespie',
 'Craig Johnson',
 'Craig Mazin',
 'Craig Moss',
 'Craig R. Baxley',
 'Craig Zobel',
 'Cristian Mungiu',
 'Curtis Hanson',
 'Cyrus Nowrasteh',
 'Cédric Klapisch',
 'D. Stevens',
 'D.J. Caruso',
 'D.W. Griffith',
 'DJ Pooh',
 'Dagur Kári',
 'Daisy von Scherler Mayer',
 'Damian Nieman',
 'Damien Chazelle',
 'Damien Dante Wayans',
 "Damien O'Donnell",
 'Damir Catic',
 'Damon Santostefano',
 'Dan Curtis',
 'Dan Cutforth',
 'Dan Fogelman',
 'Dan Gilroy',
 'Dan Harris',
 'Dan Ireland',
 'Dan Mazer',
 "Dan O'Bannon",
 'Dan Reed',
 'Dan Rush',
 'Dan Scanlon',
 'Dan St. Pierre',
 'Dan Trachtenberg',
 'Dan Zukovic',
 'Daniel Algrant',
 'Daniel Barber',
 'Daniel Barnz',
 'Daniel Espinosa',
 'Daniel Hsia',
 'Daniel Lee',
 'Daniel Mellitz',
 'Daniel Myrick',
 'Daniel Petrie, Jr.',
 'Daniel Sackheim',
 'Daniel Schechter',
 'Daniel Stamm',
 'Daniel Taplitz',
 'Danny Boyle',
 'Danny Cannon',
 'Danny DeVito',
 'Danny Leiner',
 'Danny Pang',
 'Danny Perez',
 'Danny Provenzano',
 'Danny Steinmann',
 'Dany Boon',
 'Darin Scott',
 'Darnell Martin',
 'Darrell James Roodt',
 'Darren Aronofsky',
 'Darren Grant',
 'Darren Lynn Bousman',
 'Darren Press',
 'Darren Stein',
 'Daryl Wein',
 'Dave Carroll',
 'Dave Green',
 'Dave McKean',
 'Dave Meyers',
 'Dave Payne',
 'Dave Willis',
 'David Anspaugh',
 'David Atkins',
 'David Ayer',
 'David Bowers',
 'David Boyd',
 'David Caffrey',
 'David Carson',
 'David Cronenberg',
 'David Cross',
 'David DeCoteau',
 'David Dobkin',
 'David Duchovny',
 'David E. Talbert',
 'David Evans ',
 'David F. Sandberg',
 'David Fincher',
 'David Frankel',
 'David Gelb',
 'David Gordon Green',
 'David Hackl',
 'David Hand',
 'David Hayter',
 'David Hewlett',
 'David Jacobson',
 'David Kellogg',
 'David Koepp',
 'David LaChapelle',
 'David Lam',
 'David Lean',
 'David Leland',
 'David Lowery',
 'David Lynch',
 'David M. Matthews',
 'David Mamet',
 'David McNally',
 'David Mirkin',
 'David Moreau',
 'David Nixon',
 'David Nutter',
 'David O. Russell',
 'David Oelhoffen',
 'David R. Ellis',
 'David Ray',
 'David Raynr',
 'David Robert Mitchell',
 'David Rodriguez',
 'David S. Goyer',
 'David S. Ward',
 'David Schwimmer',
 'David Silverman',
 'David Sington',
 'David Slade',
 'David Soren',
 'David Twohy',
 'David Wain',
 'David Webb Peoples',
 'David Winning',
 'David Winters',
 'David Worth',
 'David Yates',
 'David Zucker',
 'Davis Guggenheim',
 'Dax Shepard',
 'Dean DeBlois',
 'Dean Israelite',
 'Dean Parisot',
 'Dean Wright',
 'Deb Hagan',
 'Deborah Anderson',
 'Deborah Kaplan',
 'Debra Granik',
 'Deepa Mehta',
 'Demian Lichtenstein',
 'Dena Seidel',
 'Denis Villeneuve',
 'Dennie Gordon',
 'Dennis Dugan',
 'Dennis Gansel',
 'Dennis Hopper',
 'Dennis Iliadis',
 'Denys Arcand',
 'Denzel Washington',
 'Deon Taylor',
 'Derek Cianfrance',
 'Derek Yee Tung-Sing',
 'Derick Martini',
 'Derrick Borte',
 'Deryck Broom',
 'Des McAnuff',
 'Dewey Nicks',
 'Dexter Fletcher',
 'Diane English',
 'Diane Keaton',
 'Dick Richards',
 'Dito Montiel',
 'Dominic Burns',
 'Dominic Sena',
 'Dominique Othenin-Girard',
 'Don Bluth',
 'Don Coscarelli',
 'Don Mancini',
 'Don Michael Paul',
 'Don Scardino',
 'Don Siegel',
 'Don Taylor',
 'Donald Petrie',
 'Doug Atchison',
 'Doug Block',
 'Doug Lefler',
 'Doug Liman',
 'Doug McHenry',
 'Douglas Aarniokoski',
 'Douglas Cheek',
 'Douglas McGrath',
 'Douglas Trumbull',
 'Drake Doremus',
 'Drew Barrymore',
 'Drew Goddard',
 'Dror Moreh',
 'Duane Journey',
 'Duncan Jones',
 'Duncan Tucker',
 'Dustin Hoffman',
 'Dwight H. Little',
 'Dylan Bank',
 'E. Elias Merhige',
 'E.L. Katz',
 'Ed Decter',
 'Ed Gass-Donnelly',
 'Ed Harris',
 "Eddie O'Flaherty",
 'Edgar Wright',
 'Edward Burns',
 'Edward Dmytryk',
 'Edward Hall',
 'Edward Norton',
 'Edward Zwick',
 'Ekachai Uekrongtham',
 'Elaine May',
 'Eldar Rapaport',
 'Eli Craig',
 'Eli Roth',
 'Elia Kazan',
 'Elizabeth Allen Rosenbaum',
 'Elizabeth Banks',
 'Ellory Elkayem',
 'Emile Ardolino',
 'Emilio Estevez',
 'Emily Dell',
 'Emily Young',
 'Emma-Kate Croghan',
 'Enrique Begné',
 'Eric Blakeney',
 'Eric Bress',
 'Eric Brevig',
 'Eric Bross',
 'Eric Bugbee',
 'Eric Darnell',
 'Eric Eason',
 'Eric England',
 'Eric Lartigau',
 'Eric Lavaine',
 'Eric Mendelsohn',
 'Eric Nicholas',
 'Eric Schaeffer',
 'Eric Styles',
 'Eric Valette',
 'Ericson Core',
 'Erik Canuel',
 'Erik White',
 'Ernest R. Dickerson',
 'Ernie Barbarash',
 'Errol Morris',
 'Etan Cohen',
 'Eugenio Derbez',
 'Eugène Lourié',
 'Eytan Fox',
 'F. Gary Gray',
 'Fabián Bielinsky',
 'Fatih Akin',
 'Fede Alvarez',
 'Fenton Bailey',
 'Fergal Reilly',
 'Fernando Baez Mella',
 'Fernando León de Aranoa',
 'Fernando Meirelles',
 'Feroz Abbas Khan',
 'Ferzan Ozpetek',
 'Fina Torres',
 'Florent-Emilio Siri',
 'Floria Sigismondi',
 'Florian Henckel von Donnersmarck',
 'Floyd Mutrux',
 'Forest Whitaker',
 'Francesca Gregorini',
 'Francis Ford Coppola',
 'Francis Lawrence',
 'Franck Khalfoun',
 'Franco Zeffirelli',
 'Frank Borzage',
 'Frank Capra',
 'Frank Coraci',
 'Frank Darabont',
 'Frank LaLoggia',
 'Frank Lotito',
 'Frank Marshall',
 'Frank Miller',
 'Frank Nissen',
 'Frank Oz',
 'Frank Passingham',
 'Frank Perry',
 'Frank Sebastiano',
 'Frank Whaley',
 'Franklin J. Schaffner',
 'François Girard',
 'François Ozon',
 'François Truffaut',
 'Fred Dekker',
 'Fred Durst',
 'Fred Savage',
 'Fred Schepisi',
 'Fred Walton',
 'Fred Wolf',
 'Fred Zinnemann',
 'Frederik Du Chau',
 'Fritz Lang',
 'Frédéric Auburtin',
 'Fyodor Bondarchuk',
 'G.W. Pabst',
 'Gabe Ibáñez',
 'Gabriela Tagliavini',
 'Gabriele Muccino',
 'Gareth Edwards',
 'Gareth Evans',
 'Garry Marshall',
 'Garth Jennings',
 'Gary Chapman',
 'Gary David Goldberg',
 'Gary Fleder',
 'Gary Goldman',
 'Gary Halvorson',
 'Gary Hardwick',
 'Gary McKendry',
 'Gary Nelson',
 'Gary Ross',
 'Gary Sherman',
 'Gary Shore',
 'Gary Sinyor',
 'Gary Trousdale',
 'Gary Winick',
 'Gaspar Noé',
 'Gavin Hood',
 "Gavin O'Connor",
 'Gavin Wiesen',
 'Gene Quintano',
 'Gene Teigland',
 'Genndy Tartakovsky',
 'Geoff Murphy',
 'Geoffrey Sax',
 'George A. Romero',
 'George Armitage',
 'George Clooney',
 'George Cukor',
 'George Gallo',
 'George Hickenlooper',
 'George Lucas',
 'George Miller',
 'George Nolfi',
 'George P. Cosmatos',
 'George Ratliff',
 'George Roy Hill',
 'George Sidney',
 'George Stevens',
 'George T. Miller',
 'George Tillman, Jr.',
 'Georgia Hilton',
 'Gerald Potterton',
 'Gerard Johnstone',
 'Gerry Lively',
 'Gia Coppola',
 'Gideon Raff',
 'Gil Junger',
 'Gil Kenan',
 'Gilles Paquet-Brenner',
 'Gillian Armstrong',
 'Gillian Robespierre',
 'Gina Prince-Bythewood',
 'Giovanni Zelko',
 'Giuliano Montaldo',
 'Giuseppe Tornatore',
 'Glen Morgan',
 'Glenn Ficarra',
 'Gnana Rajasekaran',
 'Gonzalo López-Gallego',
 'Goran Dukic',
 'Gordon Chan',
 'Gore Verbinski',
 'Grant Heslov',
 'Greg Berlanti',
 'Greg Coolidge',
 'Greg Harrison',
 'Greg Marcks',
 'Greg Mottola',
 'Gregor Jordan',
 'Gregory Hoblit',
 'Gregory Jacobs',
 'Gregory Nava',
 'Gregory Poirier',
 'Gregory Widen',
 'Griffin Dunne',
 'Guillaume Canet',
 'Guillaume Ivernel',
 'Guillermo del Toro',
 'Gurinder Chadha',
 'Gus Van Sant',
 'Guy Hamilton',
 'Guy Maddin',
 'Guy Ritchie',
 'Gábor Csupó',
 'Gérard Krawczyk',
 'H.M. Coakley',
 'Hal Haberman',
 'Hal Needham',
 'Ham Tran',
 'Hank Braxtan',
 'Hans Canosa',
 'Hans Petter Moland',
 'Harald Reinl',
 'Harald Zwart',
 'Harley Cokeliss',
 'Harmage Singh Kalirai',
 'Harmony Korine',
 'Harold Becker',
 'Harold Cronk',
 'Harold Ramis',
 'Harry Beaumont',
 'Hart Bochner',
 'Hayao Miyazaki',
 'Hayley Cloake',
 'Heidi Ewing',
 'Henry Alex Rubin',
 'Henry Bean',
 'Henry Hathaway',
 'Henry Hobson',
 'Henry Jaglom',
 'Henry Joost',
 'Henry King',
 'Henry Koster',
 'Henry Selick',
 'Herb Freed',
 'Herbert Ross',
 'Hideaki Anno',
 'Hideo Nakata',
 'Hilary Brougher',
 'Hironobu Sakaguchi',
 'Hitoshi Matsumoto',
 'Hou Hsiao-hsien',
 'Howard Deutch',
 'Howard Hawks',
 'Howard Zieff',
 'Hoyt Yeatman',
 'Huck Botko',
 'Hue Rhodes',
 'Hugh Hudson',
 'Hugh Johnson',
 'Hugh Wilson',
 'Hunter Richards',
 'Iain Softley',
 'Ian Fitzgibbon',
 'Ian Iqbal Rashid',
 'Ian Sharp',
 'Ice Cube',
 'Ingmar Bergman',
 'Inna Evlannikova',
 'Ira Sachs',
 'Irvin Kershner',
 'Irwin Winkler',
 'Isaac Florentine',
 'Isabel Coixet',
 'István Szabó',
 'Ivan Engler',
 'Ivan Kavanagh',
 'Ivan Reitman',
 'J Blakeson',
 'J. Lee Thompson',
 'J.B. Rogers',
 'J.C. Chandor',
 'J.J. Abrams',
 'J.S. Cardone',
 'Jack Conway',
 'Jack Heller',
 'Jack Perez',
 'Jack Sholder',
 'Jack Smight',
 'Jackie Chan',
 'Jackie Earle Haley',
 'Jaco Booyens',
 'Jacob Aaron Estes',
 'Jacques Perrin',
 'Jafar Panahi',
 'Jake Goldberger',
 'Jake Kasdan',
 'Jake Paltrow',
 'Jake Schreier',
 'Jake Scott',
 'Jamaa Fanaka',
 'Jamal Hill',
 'Jamel Debbouze',
 'James Algar',
 'James Bidgood',
 'James Bobin',
 'James Bridges',
 'James Cameron',
 'James Cox',
 'James D. Stern',
 'James David Pasternak',
 'James DeMonaco',
 'James Dodson',
 'James Fargo',
 'James Foley',
 'James Frawley',
 'James Gartner',
 'James Gray',
 'James Gunn',
 'James Isaac',
 'James Ivory',
 'James Kerwin',
 'James L. Brooks',
 'James Manera',
 'James Mangold',
 'James Marsh',
 'James McTeigue',
 'James Melkonian',
 'James Mottern',
 'James Nunn',
 "James O'Brien",
 'James Ponsoldt',
 'James Schamus',
 'James Toback',
 'James Wan',
 'James Watkins',
 'James Whale',
 'James Wong',
 'Jamie Babbit',
 'Jamie Blanks',
 'Jamie Thraves',
 'Jamie Travis',
 'Jamin Winans',
 'Jan Pinkava',
 'Jan de Bont',
 'Jane Campion',
 'Janusz Kamiński',
 'Jared Hess',
 'Jason Alexander',
 'Jason Bateman',
 'Jason Connery',
 'Jason Eisener',
 'Jason Friedberg',
 'Jason Marsden',
 'Jason Miller',
 'Jason Moore',
 'Jason Reitman',
 'Jason Stone',
 'Jason Trost',
 'Jason Zada',
 'Jaume Balagueró',
 'Jaume Collet-Serra',
 'Jay Alaimo',
 'Jay Chandrasekhar',
 'Jay Duplass',
 'Jay Levey',
 'Jay Oliva',
 'Jay Roach',
 'Jay Russell',
 'Jean-François Richet',
 'Jean-Jacques Annaud',
 'Jean-Jacques Mantello',
 'Jean-Luc Godard',
 'Jean-Marc Barr',
 'Jean-Marc Vallée',
 'Jean-Marie Poiré',
 'Jean-Paul Rappeneau',
 'Jean-Pierre Jeunet',
 'Jeannot Szwarc',
 'Jeb Stuart',
 'Jeff Burr',
 'Jeff Crook',
 'Jeff Franklin',
 'Jeff Garlin',
 'Jeff Kanew',
 'Jeff Lowell',
 'Jeff Nathanson',
 'Jeff Nichols',
 'Jeff Schaffer',
 'Jeff Tremaine',
 'Jeff Wadlow',
 'Jeffrey St. Jules',
 'Jeffrey W. Byrd',
 'Jehane Noujaim',
 'Jem Cohen',
 'Jennifer Flackett',
 'Jennifer Yuh Nelson',
 'Jeremy Brock',
 'Jeremy Leven',
 'Jeremy Saulnier',
 'Jeremy Sims',
 'Jerome Elston Scott',
 'Jerry Belson',
 'Jerry Dugan',
 'Jerry Jameson',
 'Jerry Rees',
 'Jerry Zaks',
 'Jerry Zucker',
 'Jesse Dylan',
 'Jesse Peretz',
 'Jesse Vaughan',
 'Jessica Bendinger',
 'Jessie Nelson',
 'Jessy Terrero',
 'Jeta Amata',
 'Jez Butterworth',
 'Jill Culton',
 'Jill Sprecher',
 'Jim Chuchu',
 'Jim Fall',
 'Jim Field Smith',
 'Jim Gillespie',
 'Jim Goddard',
 ...]

In [90]:
def get_movies_by_director(director_name):
   
   
    
    # Filter the DataFrame to include only movies with the specified director
    movies_by_director = mov[mov['Director'].apply(lambda x: director_name in x)]
    
    # Return a new DataFrame with the desired columns
    return movies_by_director[['title', 'genres', 'cast', 'Director']]

In [91]:
get_movies_by_director('James Cameron')

,title,genres,cast,Director
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
25,Titanic,"[Drama, Romance, Thriller]","[Kate Winslet, Leonardo DiCaprio, Frances Fisher]",[James Cameron]
279,Terminator 2: Judgment Day,"[Action, Thriller, Science Fiction]","[Arnold Schwarzenegger, Linda Hamilton, Robert...",[James Cameron]
282,True Lies,"[Action, Thriller]","[Arnold Schwarzenegger, Jamie Lee Curtis, Tom ...",[James Cameron]
587,The Abyss,"[Adventure, Action, Thriller, Science Fiction]","[Ed Harris, Mary Elizabeth Mastrantonio, Micha...",[James Cameron]
2409,Aliens,"[Horror, Action, Thriller, Science Fiction]","[Sigourney Weaver, Michael Biehn, James Remar]",[James Cameron]
3444,The Terminator,"[Action, Thriller, Science Fiction]","[Arnold Schwarzenegger, Michael Biehn, Linda H...",[James Cameron]

* Recommendation based on Director movies -:

In [92]:
def recommended_Director_movies(director_name, mov, similarity):
    # Check if any movies are available for the specified director
    if mov[mov['Director'].apply(lambda x: director_name in x)].empty:
        return "No movies found for director " + director_name
    
    movie_index=  mov[mov['Director'].apply(lambda x: director_name in x)].index[0]
    distances= similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:11]
    recommended_movies = mov.iloc[[i[0] for i in movies_list]][['title', 'genres', 'cast', 'Director']]

    return recommended_movies

In [93]:
recommended_Director_movies('Gore Verbinski',mov, similarity)

,title,genres,cast,Director
12,Pirates of the Caribbean: Dead Man's Chest,"[Adventure, Fantasy, Action]","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
199,Pirates of the Caribbean: The Curse of the Bla...,"[Adventure, Fantasy, Action]","[Johnny Depp, Geoffrey Rush, Orlando Bloom]",[Gore Verbinski]
17,Pirates of the Caribbean: On Stranger Tides,"[Adventure, Action, Fantasy]","[Johnny Depp, Penélope Cruz, Ian McShane]",[Rob Marshall]
216,Life of Pi,"[Adventure, Drama, Action]","[Suraj Sharma, Irrfan Khan, Ayush Tandon]",[Ang Lee]
3573,"20,000 Leagues Under the Sea","[Adventure, Drama, Science Fiction]","[Kirk Douglas, James Mason, Paul Lukas]",[Richard Fleischer]
187,Puss in Boots,"[Action, Adventure, Animation, Family, Fantasy]","[Antonio Banderas, Salma Hayek, Zach Galifiana...",[Chris Miller]
2135,The Black Hole,"[Adventure, Family, Science Fiction, Action]","[Maximilian Schell, Anthony Perkins, Robert Fo...",[Gary Nelson]
848,The Pirates! In an Adventure with Scientists!,"[Animation, Adventure, Family, Comedy]","[Hugh Grant, Brendan Gleeson, Jeremy Piven]",[Peter Lord]
1077,The Indian in the Cupboard,"[Adventure, Family, Fantasy]","[Hal Scardino, Litefoot, Lindsay Crouse]",[Frank Oz]
109,The Chronicles of Narnia: The Voyage of the Da...,"[Adventure, Family, Fantasy]","[Skandar Keynes, Georgie Henley, Simon Pegg]",[Michael Apted]

In [94]:
mov[mov['Director'].apply(lambda x: 'Gore Verbinski' in x)]

,movie_id,title,overview,genres,keywords,cast,Director,vote_count,vote_average,cast1,cast2,cast3
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],4500,6.9,Johnny Depp,Orlando Bloom,Keira Knightley
12,58,Pirates of the Caribbean: Dead Man's Chest,"[Captain, Jack, Sparrow, works, his, way, out,...","[Adventure, Fantasy, Action]","[witch, fortune teller, bondage, exotic island...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],5246,7.0,Johnny Depp,Orlando Bloom,Keira Knightley
13,57201,The Lone Ranger,"[The, Texas, Rangers, chase, down, a, gang, of...","[Action, Adventure, Western]","[texas, horse, survivor, texas ranger, partner...","[Johnny Depp, Armie Hammer, William Fichtner]",[Gore Verbinski],2311,5.9,Johnny Depp,Armie Hammer,William Fichtner
178,44896,Rango,"[When, Rango,, a, lost, family, pet,, accident...","[Animation, Comedy, Family, Western, Adventure]","[sheriff, nevada, pet, rango, chameleon, las v...","[Johnny Depp, Isla Fisher, Ned Beatty]",[Gore Verbinski],2051,6.6,Johnny Depp,Isla Fisher,Ned Beatty
199,22,Pirates of the Caribbean: The Curse of the Bla...,"[Jack, Sparrow,, a, freewheeling, 17th-century...","[Adventure, Fantasy, Action]","[exotic island, blacksmith, east india trading...","[Johnny Depp, Geoffrey Rush, Orlando Bloom]",[Gore Verbinski],6985,7.5,Johnny Depp,Geoffrey Rush,Orlando Bloom
1186,6073,The Mexican,"[Jerry, Welbach,, a, reluctant, bagman,, has, ...","[Action, Comedy, Crime, Romance]","[kidnapping, pistol]","[Brad Pitt, Julia Roberts, James Gandolfini]",[Gore Verbinski],441,5.8,Brad Pitt,Julia Roberts,James Gandolfini
2210,6963,The Weather Man,"[A, Chicago, weather, man,, separated, from, h...","[Comedy, Drama]","[new york, chicago, midlife crisis, television...","[Nicolas Cage, Michael Caine, Hope Davis]",[Gore Verbinski],289,6.0,Nicolas Cage,Michael Caine,Hope Davis

# Movies on genres -:

In [95]:
movies['genres']

0       [Action, Adventure, Fantasy, ScienceFiction]
1                       [Adventure, Fantasy, Action]
2                         [Action, Adventure, Crime]
3                   [Action, Crime, Drama, Thriller]
4                [Action, Adventure, ScienceFiction]
                            ...
4804                       [Action, Crime, Thriller]
4805                               [Comedy, Romance]
4806               [Comedy, Drama, Romance, TVMovie]
4807                                              []
4808                                   [Documentary]
Name: genres, Length: 4806, dtype: object

In [96]:
# Create an empty list to store all genres
all_genres = []

# Iterate over each row in the 'genres' column
for row in movies['genres']:
    # Iterate over each genre in the row
    for genre in row:
        # If the genre is not already in the all_genres list, add it
        if genre not in all_genres:
            all_genres.append(genre)

# Print the final list of genres
print(all_genres)

['Action', 'Adventure', 'Fantasy', 'ScienceFiction', 'Crime', 'Drama', 'Thriller', 'Animation', 'Family', 'Western', 'Comedy', 'Romance', 'Horror', 'Mystery', 'History', 'War', 'Music', 'Documentary', 'Foreign', 'TVMovie']

In [97]:
all_genres

['Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'Crime',
 'Drama',
 'Thriller',
 'Animation',
 'Family',
 'Western',
 'Comedy',
 'Romance',
 'Horror',
 'Mystery',
 'History',
 'War',
 'Music',
 'Documentary',
 'Foreign',
 'TVMovie']

In [98]:
def movies_by_genres(genres_list):
    # Create an empty list to store all genres
    all_genres = []

    # Iterate over each row in the 'genres' column
    for row in movies['genres']:
        # Iterate over each genre in the row
        for genre in row:
        # If the genre is not already in the all_genres list, add it
            if genre not in all_genres:
                all_genres.append(genre)

    # Check if genres_list is a list or not
    if not isinstance(all_genres, list):
        print('Invalid input. Please provide a list of genres.')
        return None
    
    # Filter the DataFrame to include only movies with the specified genres
    movies_by_genres = movies[movies['genres'].apply(lambda x: all(g in x for g in genres_list))]

    
    # Check if any movies match the specified genres or not
    if movies_by_genres.empty:
        print('No movies found for the specified genres.')
        return None
    
    # Return a new DataFrame with the desired columns
    return movies_by_genres[['title', 'genres', 'cast', 'Director']]

In [99]:
genre=['Action','Adventure','Comedy']

In [100]:
movies_by_genres(genre)

,title,genres,cast,Director
55,Brave,"[Animation, Adventure, Comedy, Family, Action,...","[KellyMacdonald, JulieWalters, BillyConnolly]",[BrendaChapman]
70,Wild Wild West,"[Action, Adventure, Comedy, ScienceFiction, We...","[WillSmith, KevinKline, KennethBranagh]",[BarrySonnenfeld]
88,Big Hero 6,"[Adventure, Family, Animation, Action, Comedy]","[ScottAdsit, RyanPotter, DanielHenney]",[ChrisWilliams]
103,The Sorcerer's Apprentice,"[Fantasy, Adventure, Action, Comedy, Drama]","[NicolasCage, JayBaruchel, MonicaBellucci]",[JonTurteltaub]
121,Night at the Museum: Battle of the Smithsonian,"[Adventure, Fantasy, Action, Comedy, Family]","[BenStiller, AmyAdams, OwenWilson]",[ShawnLevy]
...,...,...,...,...
3323,Witless Protection,"[Action, Adventure, Comedy, Crime]","[LarrytheCableGuy, IvanaMiličević, JennyMcCarthy]",[CharlesRobertCarner]
3357,Action Jackson,"[Action, Adventure, Comedy, Crime, Drama]","[CarlWeathers, CraigT.Nelson, Vanity]",[CraigR.Baxley]
4000,Journey to Saturn,"[Action, Adventure, Animation, Comedy, Science...","[CasperChristensen, FrankHvam, AliKazim]",[KrestenVestbjergAndersen]
4011,Silver Medalist,"[Action, Adventure, Comedy, Drama, Foreign]","[HuangBo, KongJiu, ShaohuaMa]",[NingHao]
4321,Airborne,"[Action, Adventure, Comedy]","[ShaneMcDermott, SethGreen, BrittneyPowell]",[RobBowman]

In [107]:
movies_by_genres2(genre).index

Int64Index([  55,   70,   88,  103,  121,  131,  150,  152,  160,  164,  167,
             186,  219,  238,  241,  243,  263,  342,  350,  370,  402,  403,
             411,  457,  472,  503,  518,  531,  540,  543,  594,  596,  604,
             618,  664,  665,  683,  691,  711,  788,  831,  833,  859,  888,
             933,  992, 1015, 1027, 1047, 1080, 1103, 1158, 1194, 1259, 1299,
            1327, 1367, 1369, 1583, 1692, 1727, 1783, 1796, 1831, 1833, 1857,
            1860, 1924, 1938, 1979, 2075, 2128, 2142, 2215, 2448, 2687, 2689,
            2753, 2818, 2833, 2904, 3006, 3040, 3056, 3103, 3141, 3153, 3323,
            3357, 4000, 4011, 4321],
           dtype='int64')

In [177]:
def recommended_genres_movies(genre_list, movies, similarity):
    # Check if any movies are available for the specified director
    movies_by_genres = movies[movies['genres'].apply(lambda x: all(g in x for g in genre_list))]
    if len(movies_by_genres) == 0:
        print("No movies found that match the specified genres.")
        return None

    genre_index = movies_by_genres.index

    #movie_index = movies[movies['genres'].apply(lambda x: all(g in x for g in genre_list))].index[0]
    filtered_movies = movies_by_genres
    if len(filtered_movies) > 0:
        movie_index = filtered_movies.index[0]
    else:
        print("No movies found that match the specified genres.")

    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:11]
    genrewise_movies = movies.iloc[[i[0] for i in movies_list]][['title', 'genres', 'cast', 'Director']]

    return genrewise_movies[['title', 'genres', 'cast', 'Director']]

In [178]:
recommended_genres_movies(genre,mov,similarity)

,title,genres,cast,Director
734,The Tale of Despereaux,"[Adventure, Animation, Family]","[Matthew Broderick, Dustin Hoffman, Emma Watson]",[Robert Stevenhagen]
106,Shrek the Third,"[Fantasy, Adventure, Animation, Comedy, Family]","[Mike Myers, Eddie Murphy, Cameron Diaz]",[Chris Miller]
1444,Krull,"[Fantasy, Action, Adventure]","[Ken Marshall, Lysette Anthony, Francesca Annis]",[Peter Yates]
124,Frozen,"[Animation, Adventure, Family]","[Kristen Bell, Idina Menzel, Jonathan Groff]",[Chris Buck]
1658,Dragonball Evolution,"[Action, Adventure, Fantasy, Science Fiction, ...","[Chow Yun-fat, Justin Chatwin, Joon Park]",[James Wong]
81,Maleficent,"[Fantasy, Adventure, Action, Family, Romance]","[Angelina Jolie, Elle Fanning, Sharlto Copley]",[Robert Stromberg]
565,Shrek 2,"[Adventure, Animation, Comedy, Family, Fantasy]","[Mike Myers, Eddie Murphy, Cameron Diaz]",[Andrew Adamson]
2802,The Prisoner of Zenda,"[Adventure, Drama, Romance]","[Ronald Colman, Madeleine Carroll, Raymond Mas...",[John Cromwell]
4627,Royal Kill,"[Action, Thriller]","[Pat Morita, Eric Roberts, Gail Kim]",[Babar Ahmed]
1701,Aladdin,"[Animation, Family, Comedy, Adventure, Fantasy...","[Scott Weinger, Robin Williams, Linda Larkin]",[Ron Clements]